using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace StatePark.Models
{
  public class StateParkContext : DbContext
  {
    public DbSet<Park> Parks { get; set; }
    public DbSet<Region> Regions { get; set; }

    public StateParkContext(DbContextOptions options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<Park>()
        .HasData(
          new Park { ParkId = 1, Name = "Goose Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "NearestCity" , RegionId = 1 },
          new Park { ParkId = 2, Name = "Frenchglen Hotel State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Lakeview" , RegionId = 2 },
          new Park { ParkId = 3, Name = "Ontario State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Burns" , RegionId = 2 },
          new Park { ParkId = 4, Name = "Farewell Bend State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Ontario" , RegionId = 2 },
          new Park { ParkId = 5, Name = "Kam Wah Chung State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Ontario" , RegionId = 2 },
          new Park { ParkId = 6, Name = "Unity Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "John Day" , RegionId = 2 },
          new Park { ParkId = 7, Name = "Unity Lake State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "John Day" , RegionId = 2 },
          new Park { ParkId = 8, Name = "Clyde Holliday State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "John Day" , RegionId = 2 },
          new Park { ParkId = 9, Name = "Succor Creek State Natural Area", Type = "Natural Area", Camping = true, NearestCity = "John Day" , RegionId = 2 },
          new Park { ParkId = 10, Name = "Lake Owyhee State Park", Type = "State Park", Camping = true, NearestCity = "Nyssa" , RegionId = 2 },
          new Park { ParkId = 11, Name = "Catherine Creek State Park", Type = "State Park", Camping = true, NearestCity = "Nyssa" , RegionId = 2 },
          new Park { ParkId = 12, Name = "Hat Rock State Park", Type = "State Park", Camping = false, NearestCity = "Union" , RegionId = 2 },
          new Park { ParkId = 13, Name = "Hilgard Junction State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Umatilla" , RegionId = 2 },
          new Park { ParkId = 14, Name = "Red Bridge State Wayside", Type = "Wayside", Camping = true, NearestCity = "La Grande" , RegionId = 2 },
          new Park { ParkId = 15, Name = "Ukiah–Dale Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = true, NearestCity = "La Grande" , RegionId = 2 },
          new Park { ParkId = 16, Name = "Emigrant Springs State Heritage Area", Type = "Heritage Area", Camping = true, NearestCity = "Ukiah" , RegionId = 2 },
          new Park { ParkId = 17, Name = "Wallowa Lake Highway Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Pendleton" , RegionId = 2 },
          new Park { ParkId = 18, Name = "Wallowa River Rest Area", Type = "Rest Area", Camping = false, NearestCity = "Enterprise" , RegionId = 2 },
          new Park { ParkId = 19, Name = "Minam State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "La Grande" , RegionId = 2 },
          new Park { ParkId = 20, Name = "Wallowa Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Elgin" , RegionId = 2 },
          new Park { ParkId = 21, Name = "Iwetemlaykin State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Joseph" , RegionId = 2 },
          new Park { ParkId = 22, Name = "Casey State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Joseph" , RegionId = 1 },
          new Park { ParkId = 23, Name = "Prospect State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Medford" , RegionId = 1 },
          new Park { ParkId = 24, Name = "Joseph H. Stewart State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Prospect" , RegionId = 1 },
          new Park { ParkId = 25, Name = "The Cove Palisades State Park", Type = "State Park", Camping = true, NearestCity = "Medford" , RegionId = 3 },
          new Park { ParkId = 26, Name = "Jasper Point Campground", Type = "Campground", Camping = true, NearestCity = "Madras" , RegionId = 3 },
          new Park { ParkId = 27, Name = "Prineville Reservoir State Park", Type = "State Park", Camping = true, NearestCity = "Prineville" , RegionId = 3 },
          new Park { ParkId = 28, Name = "Heritage Landing (Deschutes)", Type = "Boat Launch", Camping = false, NearestCity = "Prineville" , RegionId = 4 },
          new Park { ParkId = 29, Name = "White River Falls State Park", Type = "State Park", Camping = false, NearestCity = "The Dalles" , RegionId = 4 },
          new Park { ParkId = 30, Name = "Deschutes River State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "The Dalles" , RegionId = 4 },
          new Park { ParkId = 31, Name = "Cline Falls State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "The Dalles" , RegionId = 3 },
          new Park { ParkId = 32, Name = "Fort Rock State Natural Area", Type = "Natural Area", Camping = true, NearestCity = "Redmond" , RegionId = 3 },
          new Park { ParkId = 33, Name = "La Pine State Park", Type = "State Park", Camping = true, NearestCity = "Fort Rock" , RegionId = 3 },
          new Park { ParkId = 34, Name = "Pilot Butte State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "La Pine" , RegionId = 3 },
          new Park { ParkId = 35, Name = "Tumalo State Park", Type = "State Park", Camping = true, NearestCity = "Bend" , RegionId = 3 },
          new Park { ParkId = 36, Name = "Peter Skene Ogden State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Bend" , RegionId = 3 },
          new Park { ParkId = 37, Name = "Smith Rock State Park", Type = "State Park", Camping = true, NearestCity = "Redmond" , RegionId = 3 },
          new Park { ParkId = 38, Name = "Booth State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Redmond" , RegionId = 1 },
          new Park { ParkId = 39, Name = "Chandler State Wayside", Type = "Wayside", Camping = false, NearestCity = "Lakeview" , RegionId = 1 },
          new Park { ParkId = 40, Name = "Geisel Monument State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Lakeview" , RegionId = 5 },
          new Park { ParkId = 41, Name = "Humbug Mountain State Park", Type = "State Park", Camping = true, NearestCity = "Gold Beach" , RegionId = 5 },
          new Park { ParkId = 42, Name = "Otter Point State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Port Orford" , RegionId = 5 },
          new Park { ParkId = 43, Name = "Paradise Point State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Gold Beach" , RegionId = 5 },
          new Park { ParkId = 44, Name = "Port Orford Heads State Park", Type = "State Park", Camping = false, NearestCity = "Port Orford" , RegionId = 5 },
          new Park { ParkId = 45, Name = "Cape Blanco State Park", Type = "State Park", Camping = true, NearestCity = "Port Orford" , RegionId = 5 },
          new Park { ParkId = 46, Name = "Bandon State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Port Orford" , RegionId = 5 },
          new Park { ParkId = 47, Name = "Coquille Myrtle Grove State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Bandon" , RegionId = 5 },
          new Park { ParkId = 48, Name = "Face Rock State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Myrtle Point" , RegionId = 5 },
          new Park { ParkId = 49, Name = "Hoffman Memorial State Wayside", Type = "Wayside", Camping = false, NearestCity = "Bandon" , RegionId = 5 },
          new Park { ParkId = 50, Name = "Seven Devils State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Myrtle Point" , RegionId = 5 },
          new Park { ParkId = 51, Name = "Bullards Beach State Park", Type = "State Park", Camping = true, NearestCity = "Bandon" , RegionId = 5 },
          new Park { ParkId = 52, Name = "Alfred A. Loeb State Park", Type = "State Park", Camping = true, NearestCity = "Bandon" , RegionId = 5 },
          new Park { ParkId = 53, Name = "Cape Sebastian State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Brookings" , RegionId = 5 },
          new Park { ParkId = 54, Name = "Crissey Field State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Gold Beach" , RegionId = 5 },
          new Park { ParkId = 55, Name = "McVay Rock State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Brookings" , RegionId = 5 },
          new Park { ParkId = 56, Name = "Pistol River State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Brookings" , RegionId = 5 },
          new Park { ParkId = 57, Name = "Samuel H. Boardman State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Gold Beach" , RegionId = 5 },
          new Park { ParkId = 58, Name = "Winchuck State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Brookings" , RegionId = 5 },
          new Park { ParkId = 59, Name = "Harris Beach State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Brookings" , RegionId = 5 },
          new Park { ParkId = 60, Name = "Alderwood State Wayside", Type = "Wayside", Camping = false, NearestCity = "Brookings" , RegionId = 6 },
          new Park { ParkId = 61, Name = "Elijah Bristow State Park", Type = "State Park", Camping = false, NearestCity = "Junction City" , RegionId = 6 },
          new Park { ParkId = 62, Name = "Washburne State Wayside", Type = "Wayside", Camping = false, NearestCity = "Eugene" , RegionId = 6 },
          new Park { ParkId = 63, Name = "Mongold Day-Use Area", Type = "Boat Launch", Camping = false, NearestCity = "Junction City" , RegionId = 6 },
          new Park { ParkId = 64, Name = "North Santiam State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Detroit" , RegionId = 6 },
          new Park { ParkId = 65, Name = "Detroit Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Mill City" , RegionId = 6 },
          new Park { ParkId = 66, Name = "Cape Arago State Park", Type = "State Park", Camping = false, NearestCity = "Detroit" , RegionId = 5 },
          new Park { ParkId = 67, Name = "Golden and Silver Falls State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Coos Bay" , RegionId = 5 },
          new Park { ParkId = 68, Name = "Shore Acres State Park", Type = "State Park", Camping = false, NearestCity = "Coos Bay" , RegionId = 5 },
          new Park { ParkId = 69, Name = "William M. Tugman State Park", Type = "State Park", Camping = true, NearestCity = "Coos Bay" , RegionId = 5 },
          new Park { ParkId = 70, Name = "Sunset Bay State Park", Type = "State Park", Camping = true, NearestCity = "Reedsport" , RegionId = 5 },
          new Park { ParkId = 71, Name = "Illinois River Forks State Park", Type = "State Park", Camping = false, NearestCity = "Coos Bay" , RegionId = 1 },
          new Park { ParkId = 72, Name = "TouVelle State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Cave Junction" , RegionId = 1 },
          new Park { ParkId = 73, Name = "Tub Springs State Wayside", Type = "Wayside", Camping = false, NearestCity = "Medford" , RegionId = 1 },
          new Park { ParkId = 74, Name = "Wolf Creek Inn State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Ashland" , RegionId = 1 },
          new Park { ParkId = 75, Name = "Valley of the Rogue State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Grants Pass" , RegionId = 1 },
          new Park { ParkId = 76, Name = "Bald Peak State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Grants Pass" , RegionId = 4 },
          new Park { ParkId = 77, Name = "Molalla River State Park", Type = "State Park", Camping = false, NearestCity = "Newberg" , RegionId = 4 },
          new Park { ParkId = 78, Name = "Champoeg State Heritage Area", Type = "Heritage Area", Camping = true, NearestCity = "Canby" , RegionId = 6 },
          new Park { ParkId = 79, Name = "Beaver Creek State Natural Area", Type = "State Park", Camping = false, NearestCity = "Newberg" , RegionId = 7 },
          new Park { ParkId = 80, Name = "Bolon Island Tideways State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 81, Name = "Darlingtonia State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Reedsport" , RegionId = 7 },
          new Park { ParkId = 82, Name = "Governor Patterson Memorial State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Florence" , RegionId = 7 },
          new Park { ParkId = 83, Name = "Umpqua Lighthouse State Park", Type = "State Park", Camping = true, NearestCity = "Waldport" , RegionId = 7 },
          new Park { ParkId = 84, Name = "Beachside State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "Reedsport" , RegionId = 7 },
          new Park { ParkId = 85, Name = "Carl G. Washburne Memorial State Park", Type = "State Park", Camping = true, NearestCity = "Waldport" , RegionId = 7 },
          new Park { ParkId = 86, Name = "Heceta Head Lighthouse State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Florence" , RegionId = 7 },
          new Park { ParkId = 87, Name = "Muriel O. Ponsler Memorial State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Florence" , RegionId = 7 },
          new Park { ParkId = 88, Name = "Neptune State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Florence" , RegionId = 7 },
          new Park { ParkId = 89, Name = "Smelt Sands State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Yachats" , RegionId = 7 },
          new Park { ParkId = 90, Name = "Tokatee Klootchman State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Yachats" , RegionId = 7 },
          new Park { ParkId = 91, Name = "Stonefield Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Florence" , RegionId = 7 },
          new Park { ParkId = 92, Name = "W. B. Nelson State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Yachats" , RegionId = 7 },
          new Park { ParkId = 93, Name = "Yachats Ocean Road State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Waldport" , RegionId = 7 },
          new Park { ParkId = 94, Name = "Yachats State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Yachats" , RegionId = 7 },
          new Park { ParkId = 95, Name = "Jessie M. Honeyman Memorial State Park", Type = "State Park", Camping = true, NearestCity = "Yachats" , RegionId = 7 },
          new Park { ParkId = 96, Name = "Erratic Rock State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Florence" , RegionId = 6 },
          new Park { ParkId = 97, Name = "Holman State Wayside", Type = "Wayside", Camping = false, NearestCity = "Sheridan" , RegionId = 6 },
          new Park { ParkId = 98, Name = "Maud Williamson State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Salem" , RegionId = 6 },
          new Park { ParkId = 99, Name = "Sarah Helmick State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Salem" , RegionId = 6 },
          new Park { ParkId = 100, Name = "Willamette Mission State Park", Type = "State Park", Camping = false, NearestCity = "Monmouth" , RegionId = 6 },
          new Park { ParkId = 101, Name = "Bonnie Lure State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Salem" , RegionId = 4 },
          new Park { ParkId = 102, Name = "Mary S. Young State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Estacada" , RegionId = 4 },
          new Park { ParkId = 103, Name = "Milo McIver State Park", Type = "State Park", Camping = true, NearestCity = "West Linn" , RegionId = 4 },
          new Park { ParkId = 104, Name = "Tryon Creek State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Estacada" , RegionId = 4 },
          new Park { ParkId = 105, Name = "Banks–Vernonia State Trail", Type = "State Trail", Camping = false, NearestCity = "Portland" , RegionId = 4 },
          new Park { ParkId = 106, Name = "Ainsworth State Park", Type = "State Park", Camping = true, NearestCity = "Vernonia" , RegionId = 4 },
          new Park { ParkId = 107, Name = "Benson State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Multnomah Falls" , RegionId = 4 },
          new Park { ParkId = 108, Name = "Bridal Veil Falls State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Multnomah Falls" , RegionId = 4 },
          new Park { ParkId = 109, Name = "Crown Point State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Multnomah Falls" , RegionId = 4 },
          new Park { ParkId = 110, Name = "Dabney State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Troutdale" , RegionId = 4 },
          new Park { ParkId = 111, Name = "George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)", Type = "Natural Area", Camping = false, NearestCity = "Troutdale" , RegionId = 4 },
          new Park { ParkId = 112, Name = "Guy W. Talbot State Park", Type = "State Park", Camping = false, NearestCity = "Troutdale" , RegionId = 4 },
          new Park { ParkId = 113, Name = "Historic Columbia River Highway State Trail", Type = "State Trail", Camping = false, NearestCity = "Troutdale" , RegionId = 4 },
          new Park { ParkId = 114, Name = "John B. Yeon State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Cascade Locks" , RegionId = 4 },
          new Park { ParkId = 115, Name = "Koberg Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Cascade Locks" , RegionId = 4 },
          new Park { ParkId = 116, Name = "Lewis and Clark State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Hood River" , RegionId = 4 },
          new Park { ParkId = 117, Name = "Mayer State Park", Type = "State Park", Camping = false, NearestCity = "Troutdale" , RegionId = 4 },
          new Park { ParkId = 118, Name = "Memaloose State Park", Type = "State Park", Camping = true, NearestCity = "The Dalles" , RegionId = 4 },
          new Park { ParkId = 119, Name = "Portland Women's Forum State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "The Dalles" , RegionId = 4 },
          new Park { ParkId = 120, Name = "Seneca Fouts Memorial State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Troutdale" , RegionId = 4 },
          new Park { ParkId = 121, Name = "Shepperd's Dell State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Hood River" , RegionId = 4 },
          new Park { ParkId = 122, Name = "Sheridan State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Multnomah Falls" , RegionId = 4 },
          new Park { ParkId = 123, Name = "Starvation Creek State Park", Type = "State Park", Camping = false, NearestCity = "Cascade Locks" , RegionId = 4 },
          new Park { ParkId = 124, Name = "Viento State Park", Type = "State Park", Camping = true, NearestCity = "Hood River" , RegionId = 4 },
          new Park { ParkId = 125, Name = "Vinzenz Lausmann Memorial State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Hood River" , RegionId = 4 },
          new Park { ParkId = 126, Name = "Wygant State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Hood River" , RegionId = 4 },
          new Park { ParkId = 127, Name = "Rooster Rock State Park", Type = "State Park", Camping = false, NearestCity = "Hood River" , RegionId = 4 },
          new Park { ParkId = 128, Name = "Bradley State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Multnomah Falls" , RegionId = 8 },
          new Park { ParkId = 129, Name = "Del Rey Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Astoria" , RegionId = 8 },
          new Park { ParkId = 130, Name = "Fort Stevens State Park", Type = "State Park", Camping = true, NearestCity = "Gearhart" , RegionId = 8 },
          new Park { ParkId = 131, Name = "Cape Kiwanda State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Astoria" , RegionId = 8 },
          new Park { ParkId = 132, Name = "Cape Meares State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Pacific City" , RegionId = 8 },
          new Park { ParkId = 133, Name = "Oceanside Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Tillamook" , RegionId = 8 },
          new Park { ParkId = 134, Name = "Bob Straub State Park", Type = "State Park", Camping = false, NearestCity = "Tillamook" , RegionId = 8 },
          new Park { ParkId = 135, Name = "Cape Lookout State Park", Type = "State Park", Camping = true, NearestCity = "Pacific City" , RegionId = 8 },
          new Park { ParkId = 136, Name = "Arcadia Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Tillamook" , RegionId = 8 },
          new Park { ParkId = 137, Name = "Ecola State Park", Type = "State Park", Camping = false, NearestCity = "Cannon Beach" , RegionId = 8 },
          new Park { ParkId = 138, Name = "Golden State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Cannon Beach" , RegionId = 1 },
          new Park { ParkId = 139, Name = "Hug Point State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Grants Pass" , RegionId = 8 },
          new Park { ParkId = 140, Name = "Manhattan Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Cannon Beach" , RegionId = 8 },
          new Park { ParkId = 141, Name = "Oswald West State Park", Type = "State Park", Camping = false, NearestCity = "Rockaway Beach" , RegionId = 8 },
          new Park { ParkId = 142, Name = "Saddle Mountain State Natural Area", Type = "Natural Area", Camping = true, NearestCity = "Cannon Beach" , RegionId = 8 },
          new Park { ParkId = 143, Name = "Tolovana Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Seaside" , RegionId = 8 },
          new Park { ParkId = 144, Name = "Nehalem Bay State Park", Type = "State Park", Camping = true, NearestCity = "Cannon Beach" , RegionId = 8 },
          new Park { ParkId = 145, Name = "Alsea Bay Historic Interpretive Center", Type = "Interpretive Center", Camping = false, NearestCity = "Manzanita" , RegionId = 7 },
          new Park { ParkId = 146, Name = "Driftwood Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Waldport" , RegionId = 7 },
          new Park { ParkId = 147, Name = "Lost Creek State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Waldport" , RegionId = 7 },
          new Park { ParkId = 148, Name = "Ona Beach State Park", Type = "State Park", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 149, Name = "Seal Rock State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 150, Name = "Yaquina Bay State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 151, Name = "South Beach State Park", Type = "State Park", Camping = true, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 152, Name = "Cascadia State Park", Type = "State Park", Camping = true, NearestCity = "Newport" , RegionId = 6 },
          new Park { ParkId = 153, Name = "Silver Falls State Park", Type = "State Park", Camping = true, NearestCity = "Sweet Home" , RegionId = 6 },
          new Park { ParkId = 154, Name = "Agate Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Silverton" , RegionId = 7 },
          new Park { ParkId = 155, Name = "Boiler Bay State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 156, Name = "D River State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Depoe Bay" , RegionId = 8 },
          new Park { ParkId = 157, Name = "Devils Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Lincoln City" , RegionId = 8 },
          new Park { ParkId = 158, Name = "Devils Punch Bowl State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Lincoln City" , RegionId = 7 },
          new Park { ParkId = 159, Name = "Ellmaker State Wayside", Type = "Wayside", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 160, Name = "Fogarty Creek State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Newport" , RegionId = 7 },
          new Park { ParkId = 161, Name = "Gleneden Beach State Recreation Site", Type = "Recreation Area", Camping = false, NearestCity = "Depoe Bay" , RegionId = 7 },
          new Park { ParkId = 162, Name = "H. B. Van Duzer Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Lincoln City" , RegionId = 8 },
          new Park { ParkId = 163, Name = "Neskowin Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Lincoln City" , RegionId = 8 },
          new Park { ParkId = 164, Name = "Otter Crest State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Neskowin" , RegionId = 7 },
          new Park { ParkId = 165, Name = "Roads End State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" , RegionId = 8 },
          new Park { ParkId = 166, Name = "Beverly Beach State Park", Type = "State Park", Camping = true, NearestCity = "Lincoln City" , RegionId = 7 },
          new Park { ParkId = 167, Name = "Collier Memorial State Park", Type = "State Park", Camping = true, NearestCity = "Newport" , RegionId = 1 },
          new Park { ParkId = 168, Name = "Jackson F. Kimball State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "Klamath Falls" , RegionId = 1 },
          new Park { ParkId = 169, Name = "OC&E Woods Line State Trail", Type = "State Trail", Camping = false, NearestCity = "Fort Klamath" , RegionId = 1 },
          new Park { ParkId = 170, Name = "South Jetty (South Beach)", Type = "Beach Access", Camping = false, NearestCity = "Klamath Falls" , RegionId = 7 },
          new Park { ParkId = 171, Name = "Blue Mountain Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Newport" , RegionId = 2 },
          new Park { ParkId = 172, Name = "Battle Mountain Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "La Grande" , RegionId = 2 },
          new Park { ParkId = 173, Name = "Sumpter Valley Dredge State Heritage Area", Type = "Heritage Area", Camping = false, NearestCity = "Ukiah" , RegionId = 2 },
          new Park { ParkId = 174, Name = "Fall Creek State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "Baker City" , RegionId = 6 },
          new Park { ParkId = 175, Name = "Lowell State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Springfield" , RegionId = 6 },
          new Park { ParkId = 176, Name = "Jasper State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Springfield" , RegionId = 6 },
          new Park { ParkId = 177, Name = "Dexter State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Springfield" , RegionId = 6 },
          new Park { ParkId = 178, Name = "Munson Creek Falls State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Springfield" , RegionId = 8 },
          new Park { ParkId = 179, Name = "Willamette Stone State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Tillamook" , RegionId = 4 },
          new Park { ParkId = 180, Name = "Umpqua State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Portland" , RegionId = 5 },
          new Park { ParkId = 181, Name = "Clay Myers State Natural Area at Whalen Island", Type = "Natural Area", Camping = false, NearestCity = "Reedsport" , RegionId = 8 },
          new Park { ParkId = 182, Name = "Fort Rock Cave (Near Fort Rock State Natural Area)", Type = "National Historic Landmark", Camping = false, NearestCity = "Pacific City" , RegionId = 3 },
          new Park { ParkId = 183, Name = "Government Island State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Fort Rock" , RegionId = 4 },
          new Park { ParkId = 184, Name = "Sunset Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Portland" , RegionId = 8 },
          new Park { ParkId = 185, Name = "Whale Watching Center", Type = "Guided Ocean Viewpoint", Camping = false, NearestCity = "Astoria" , RegionId = 7 },
          new Park { ParkId = 186, Name = "Rocky Creek State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Depoe Bay" , RegionId = 7 },
          new Park { ParkId = 187, Name = "Fort Yamhill State Heritage Area", Type = "Heritage Area", Camping = false, NearestCity = "Depoe Bay" , RegionId = 6 },
          new Park { ParkId = 188, Name = "L. L. 'Stub' Stewart State Park", Type = "State Park", Camping = true, NearestCity = "Grand Ronde" , RegionId = 4 },
          new Park { ParkId = 189, Name = "Thompson's Mills State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Vernonia" , RegionId = 6 },
          new Park { ParkId = 190, Name = "State Capitol State Park", Type = "State Park", Camping = false, NearestCity = "Shedd" , RegionId = 6 },
          new Park { ParkId = 191, Name = "Arizona Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Salem" , RegionId = 5 },
          new Park { ParkId = 192, Name = "Bates State Park", Type = "State Park", Camping = false, NearestCity = "Port Orford" , RegionId = 2 },
          new Park { ParkId = 193, Name = "Ochoco State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Prairie City" , RegionId = 3 },
          new Park { ParkId = 194, Name = "Dyer State Wayside", Type = "Wayside", Camping = false, NearestCity = "Prineville" , RegionId = 2 },
          new Park { ParkId = 195, Name = "Pete French Round Barn State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Condon" , RegionId = 2 },
          new Park { ParkId = 196, Name = "Cottonwood Canyon State Park", Type = "State Park", Camping = false, NearestCity = "New Princeton" , RegionId = 3 },
          new Park { ParkId = 197, Name = "Sitka Sedge State Natural Area", Type = "Natural Site", Camping = false, NearestCity = "Moro" , RegionId = 8 }
        );

        builder.Entity<Region>()
          .HasData(
            new Region { RegionId =1, Name = "Southern Oregon"},
            new Region { RegionId =2, Name = "Eastern Oregon"},
            new Region { RegionId =3, Name = "Central Oregon"},
            new Region { RegionId =4, Name = "Portland/Columbia Gorge"},
            new Region { RegionId =5, Name = "South Coast"},
            new Region { RegionId =6, Name = "Willamette Valley"},
            new Region { RegionId =7, Name = "Central Coast"},
            new Region { RegionId =8, Name = "North Coast"}
          );
      }
    }
}