using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace StatePark.Models
{
  public class StateParkContext : DbContext
  {
    public DbSet<Park> Parks { get; set; }
    public DbSet<Region> Regions { get; set; }
    public DbSet<ParkRegion> ParkRegions { get; set; }

    public StateParkContext(DbContextOptions options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<Park>()
        .HasData(
          new Park { ParkId = 1, Name = "Goose Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Lakeview" },
          new Park { ParkId = 2, Name = "Frenchglen Hotel State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Burns" },
          new Park { ParkId = 3, Name = "Ontario State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Ontario" },
          new Park { ParkId = 4, Name = "Farewell Bend State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Ontario" },
          new Park { ParkId = 5, Name = "Kam Wah Chung State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "John Day" },
          new Park { ParkId = 6, Name = "Unity Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "John Day" },
          new Park { ParkId = 7, Name = "Unity Lake State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "John Day" },
          new Park { ParkId = 8, Name = "Clyde Holliday State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "John Day" },
          new Park { ParkId = 9, Name = "Succor Creek State Natural Area", Type = "Natural Area", Camping = true, NearestCity = "Nyssa" },
          new Park { ParkId = 10, Name = "Lake Owyhee State Park", Type = "State Park", Camping = true, NearestCity = "Nyssa" },
          new Park { ParkId = 11, Name = "Catherine Creek State Park", Type = "State Park", Camping = true, NearestCity = "Union" },
          new Park { ParkId = 12, Name = "Hat Rock State Park", Type = "State Park", Camping = false, NearestCity = "Umatilla" },
          new Park { ParkId = 13, Name = "Hilgard Junction State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "La Grande" },
          new Park { ParkId = 14, Name = "Red Bridge State Wayside", Type = "Wayside", Camping = true, NearestCity = "La Grande" },
          new Park { ParkId = 15, Name = "Ukiah–Dale Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = true, NearestCity = "Ukiah" },
          new Park { ParkId = 16, Name = "Emigrant Springs State Heritage Area", Type = "Heritage Area", Camping = true, NearestCity = "Pendleton" },
          new Park { ParkId = 17, Name = "Wallowa Lake Highway Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Enterprise" },
          new Park { ParkId = 18, Name = "Wallowa River Rest Area", Type = "Rest Area", Camping = false, NearestCity = "La Grande" },
          new Park { ParkId = 19, Name = "Minam State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Elgin" },
          new Park { ParkId = 20, Name = "Wallowa Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Joseph" },
          new Park { ParkId = 21, Name = "Iwetemlaykin State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Joseph" },
          new Park { ParkId = 22, Name = "Casey State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Medford" },
          new Park { ParkId = 23, Name = "Prospect State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Prospect" },
          new Park { ParkId = 24, Name = "Joseph H. Stewart State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Medford" },
          new Park { ParkId = 25, Name = "The Cove Palisades State Park", Type = "State Park", Camping = true, NearestCity = "Madras" },
          new Park { ParkId = 26, Name = "Jasper Point Campground", Type = "Campground", Camping = true, NearestCity = "Prineville" },
          new Park { ParkId = 27, Name = "Prineville Reservoir State Park", Type = "State Park", Camping = true, NearestCity = "Prineville" },
          new Park { ParkId = 28, Name = "Heritage Landing (Deschutes)", Type = "Boat Launch", Camping = false, NearestCity = "The Dalles" },
          new Park { ParkId = 29, Name = "White River Falls State Park", Type = "State Park", Camping = false, NearestCity = "The Dalles" },
          new Park { ParkId = 30, Name = "Deschutes River State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "The Dalles" },
          new Park { ParkId = 31, Name = "Cline Falls State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Redmond" },
          new Park { ParkId = 32, Name = "Fort Rock State Natural Area", Type = "Natural Area", Camping = true, NearestCity = "Fort Rock" },
          new Park { ParkId = 33, Name = "La Pine State Park", Type = "State Park", Camping = true, NearestCity = "La Pine" },
          new Park { ParkId = 34, Name = "Pilot Butte State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Bend" },
          new Park { ParkId = 35, Name = "Tumalo State Park", Type = "State Park", Camping = true, NearestCity = "Bend" },
          new Park { ParkId = 36, Name = "Peter Skene Ogden State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Redmond" },
          new Park { ParkId = 37, Name = "Smith Rock State Park", Type = "State Park", Camping = true, NearestCity = "Redmond" },
          new Park { ParkId = 38, Name = "Booth State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Lakeview" },
          new Park { ParkId = 39, Name = "Chandler State Wayside", Type = "Wayside", Camping = false, NearestCity = "Lakeview" },
          new Park { ParkId = 40, Name = "Geisel Monument State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Gold Beach" },
          new Park { ParkId = 41, Name = "Humbug Mountain State Park", Type = "State Park", Camping = true, NearestCity = "Port Orford" },
          new Park { ParkId = 42, Name = "Otter Point State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Gold Beach" },
          new Park { ParkId = 43, Name = "Paradise Point State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Port Orford" },
          new Park { ParkId = 44, Name = "Port Orford Heads State Park", Type = "State Park", Camping = false, NearestCity = "Port Orford" },
          new Park { ParkId = 45, Name = "Cape Blanco State Park", Type = "State Park", Camping = true, NearestCity = "Port Orford" },
          new Park { ParkId = 46, Name = "Bandon State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Bandon" },
          new Park { ParkId = 47, Name = "Coquille Myrtle Grove State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Myrtle Point" },
          new Park { ParkId = 48, Name = "Face Rock State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Bandon" },
          new Park { ParkId = 49, Name = "Hoffman Memorial State Wayside", Type = "Wayside", Camping = false, NearestCity = "Myrtle Point" },
          new Park { ParkId = 50, Name = "Seven Devils State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Bandon" },
          new Park { ParkId = 51, Name = "Bullards Beach State Park", Type = "State Park", Camping = true, NearestCity = "Bandon" },
          new Park { ParkId = 52, Name = "Alfred A. Loeb State Park", Type = "State Park", Camping = true, NearestCity = "Brookings" },
          new Park { ParkId = 53, Name = "Cape Sebastian State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Gold Beach" },
          new Park { ParkId = 54, Name = "Crissey Field State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Brookings" },
          new Park { ParkId = 55, Name = "McVay Rock State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Brookings" },
          new Park { ParkId = 56, Name = "Pistol River State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Gold Beach" },
          new Park { ParkId = 57, Name = "Samuel H. Boardman State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Brookings" },
          new Park { ParkId = 58, Name = "Winchuck State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Brookings" },
          new Park { ParkId = 59, Name = "Harris Beach State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Brookings" },
          new Park { ParkId = 60, Name = "Alderwood State Wayside", Type = "Wayside", Camping = false, NearestCity = "Junction City" },
          new Park { ParkId = 61, Name = "Elijah Bristow State Park", Type = "State Park", Camping = false, NearestCity = "Eugene" },
          new Park { ParkId = 62, Name = "Washburne State Wayside", Type = "Wayside", Camping = false, NearestCity = "Junction City" },
          new Park { ParkId = 63, Name = "Mongold Day-Use Area", Type = "Boat Launch", Camping = false, NearestCity = "Detroit" },
          new Park { ParkId = 64, Name = "North Santiam State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Mill City" },
          new Park { ParkId = 65, Name = "Detroit Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Detroit" },
          new Park { ParkId = 66, Name = "Cape Arago State Park", Type = "State Park", Camping = false, NearestCity = "Coos Bay" },
          new Park { ParkId = 67, Name = "Golden and Silver Falls State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Coos Bay" },
          new Park { ParkId = 68, Name = "Shore Acres State Park", Type = "State Park", Camping = false, NearestCity = "Coos Bay" },
          new Park { ParkId = 69, Name = "William M. Tugman State Park", Type = "State Park", Camping = true, NearestCity = "Reedsport" },
          new Park { ParkId = 70, Name = "Sunset Bay State Park", Type = "State Park", Camping = true, NearestCity = "Coos Bay" },
          new Park { ParkId = 71, Name = "Illinois River Forks State Park", Type = "State Park", Camping = false, NearestCity = "Cave Junction" },
          new Park { ParkId = 72, Name = "TouVelle State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Medford" },
          new Park { ParkId = 73, Name = "Tub Springs State Wayside", Type = "Wayside", Camping = false, NearestCity = "Ashland" },
          new Park { ParkId = 74, Name = "Wolf Creek Inn State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Grants Pass" },
          new Park { ParkId = 75, Name = "Valley of the Rogue State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Grants Pass" },
          new Park { ParkId = 76, Name = "Bald Peak State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Newberg" },
          new Park { ParkId = 77, Name = "Molalla River State Park", Type = "State Park", Camping = false, NearestCity = "Canby" },
          new Park { ParkId = 78, Name = "Champoeg State Heritage Area", Type = "Heritage Area", Camping = true, NearestCity = "Newberg" },
          new Park { ParkId = 79, Name = "Beaver Creek State Natural Area", Type = "State Park", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 80, Name = "Bolon Island Tideways State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Reedsport" },
          new Park { ParkId = 81, Name = "Darlingtonia State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Florence" },
          new Park { ParkId = 82, Name = "Governor Patterson Memorial State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Waldport" },
          new Park { ParkId = 83, Name = "Umpqua Lighthouse State Park", Type = "State Park", Camping = true, NearestCity = "Reedsport" },
          new Park { ParkId = 84, Name = "Beachside State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "Waldport" },
          new Park { ParkId = 85, Name = "Carl G. Washburne Memorial State Park", Type = "State Park", Camping = true, NearestCity = "Florence" },
          new Park { ParkId = 86, Name = "Heceta Head Lighthouse State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Florence" },
          new Park { ParkId = 87, Name = "Muriel O. Ponsler Memorial State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Florence" },
          new Park { ParkId = 88, Name = "Neptune State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Yachats" },
          new Park { ParkId = 89, Name = "Smelt Sands State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Yachats" },
          new Park { ParkId = 90, Name = "Tokatee Klootchman State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Florence" },
          new Park { ParkId = 91, Name = "Stonefield Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Yachats" },
          new Park { ParkId = 92, Name = "W. B. Nelson State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Waldport" },
          new Park { ParkId = 93, Name = "Yachats Ocean Road State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Yachats" },
          new Park { ParkId = 94, Name = "Yachats State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Yachats" },
          new Park { ParkId = 95, Name = "Jessie M. Honeyman Memorial State Park", Type = "State Park", Camping = true, NearestCity = "Florence" },
          new Park { ParkId = 96, Name = "Erratic Rock State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Sheridan" },
          new Park { ParkId = 97, Name = "Holman State Wayside", Type = "Wayside", Camping = false, NearestCity = "Salem" },
          new Park { ParkId = 98, Name = "Maud Williamson State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Salem" },
          new Park { ParkId = 99, Name = "Sarah Helmick State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Monmouth" },
          new Park { ParkId = 100, Name = "Willamette Mission State Park", Type = "State Park", Camping = false, NearestCity = "Salem" },
          new Park { ParkId = 101, Name = "Bonnie Lure State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Estacada" },
          new Park { ParkId = 102, Name = "Mary S. Young State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "West Linn" },
          new Park { ParkId = 103, Name = "Milo McIver State Park", Type = "State Park", Camping = true, NearestCity = "Estacada" },
          new Park { ParkId = 104, Name = "Tryon Creek State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Portland" },
          new Park { ParkId = 105, Name = "Banks–Vernonia State Trail", Type = "State Trail", Camping = false, NearestCity = "Vernonia" },
          new Park { ParkId = 106, Name = "Ainsworth State Park", Type = "State Park", Camping = true, NearestCity = "Multnomah Falls" },
          new Park { ParkId = 107, Name = "Benson State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Multnomah Falls" },
          new Park { ParkId = 108, Name = "Bridal Veil Falls State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Multnomah Falls" },
          new Park { ParkId = 109, Name = "Crown Point State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Troutdale" },
          new Park { ParkId = 110, Name = "Dabney State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Troutdale" },
          new Park { ParkId = 111, Name = "George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)", Type = "Natural Area", Camping = false, NearestCity = "Troutdale" },
          new Park { ParkId = 112, Name = "Guy W. Talbot State Park", Type = "State Park", Camping = false, NearestCity = "Troutdale" },
          new Park { ParkId = 113, Name = "Historic Columbia River Highway State Trail", Type = "State Trail", Camping = false, NearestCity = "Cascade Locks" },
          new Park { ParkId = 114, Name = "John B. Yeon State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Cascade Locks" },
          new Park { ParkId = 115, Name = "Koberg Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Hood River" },
          new Park { ParkId = 116, Name = "Lewis and Clark State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Troutdale" },
          new Park { ParkId = 117, Name = "Mayer State Park", Type = "State Park", Camping = false, NearestCity = "The Dalles" },
          new Park { ParkId = 118, Name = "Memaloose State Park", Type = "State Park", Camping = true, NearestCity = "The Dalles" },
          new Park { ParkId = 119, Name = "Portland Women's Forum State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Troutdale" },
          new Park { ParkId = 120, Name = "Seneca Fouts Memorial State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Hood River" },
          new Park { ParkId = 121, Name = "Shepperd's Dell State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Multnomah Falls" },
          new Park { ParkId = 122, Name = "Sheridan State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Cascade Locks" },
          new Park { ParkId = 123, Name = "Starvation Creek State Park", Type = "State Park", Camping = false, NearestCity = "Hood River" },
          new Park { ParkId = 124, Name = "Viento State Park", Type = "State Park", Camping = true, NearestCity = "Hood River" },
          new Park { ParkId = 125, Name = "Vinzenz Lausmann Memorial State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Hood River" },
          new Park { ParkId = 126, Name = "Wygant State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Hood River" },
          new Park { ParkId = 127, Name = "Rooster Rock State Park", Type = "State Park", Camping = false, NearestCity = "Multnomah Falls" },
          new Park { ParkId = 128, Name = "Bradley State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Astoria" },
          new Park { ParkId = 129, Name = "Del Rey Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Gearhart" },
          new Park { ParkId = 130, Name = "Fort Stevens State Park", Type = "State Park", Camping = true, NearestCity = "Astoria" },
          new Park { ParkId = 131, Name = "Cape Kiwanda State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Pacific City" },
          new Park { ParkId = 132, Name = "Cape Meares State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Tillamook" },
          new Park { ParkId = 133, Name = "Oceanside Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Tillamook" },
          new Park { ParkId = 134, Name = "Bob Straub State Park", Type = "State Park", Camping = false, NearestCity = "Pacific City" },
          new Park { ParkId = 135, Name = "Cape Lookout State Park", Type = "State Park", Camping = true, NearestCity = "Tillamook" },
          new Park { ParkId = 136, Name = "Arcadia Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Cannon Beach" },
          new Park { ParkId = 137, Name = "Ecola State Park", Type = "State Park", Camping = false, NearestCity = "Cannon Beach" },
          new Park { ParkId = 138, Name = "Golden State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Grants Pass" },
          new Park { ParkId = 139, Name = "Hug Point State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Cannon Beach" },
          new Park { ParkId = 140, Name = "Manhattan Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Rockaway Beach" },
          new Park { ParkId = 141, Name = "Oswald West State Park", Type = "State Park", Camping = false, NearestCity = "Cannon Beach" },
          new Park { ParkId = 142, Name = "Saddle Mountain State Natural Area", Type = "Natural Area", Camping = true, NearestCity = "Seaside" },
          new Park { ParkId = 143, Name = "Tolovana Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Cannon Beach" },
          new Park { ParkId = 144, Name = "Nehalem Bay State Park", Type = "State Park", Camping = true, NearestCity = "Manzanita" },
          new Park { ParkId = 145, Name = "Alsea Bay Historic Interpretive Center", Type = "Interpretive Center", Camping = false, NearestCity = "Waldport" },
          new Park { ParkId = 146, Name = "Driftwood Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Waldport" },
          new Park { ParkId = 147, Name = "Lost Creek State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 148, Name = "Ona Beach State Park", Type = "State Park", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 149, Name = "Seal Rock State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 150, Name = "Yaquina Bay State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 151, Name = "South Beach State Park", Type = "State Park", Camping = true, NearestCity = "Newport" },
          new Park { ParkId = 152, Name = "Cascadia State Park", Type = "State Park", Camping = true, NearestCity = "Sweet Home" },
          new Park { ParkId = 153, Name = "Silver Falls State Park", Type = "State Park", Camping = true, NearestCity = "Silverton" },
          new Park { ParkId = 154, Name = "Agate Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 155, Name = "Boiler Bay State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Depoe Bay" },
          new Park { ParkId = 156, Name = "D River State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Lincoln City" },
          new Park { ParkId = 157, Name = "Devils Lake State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Lincoln City" },
          new Park { ParkId = 158, Name = "Devils Punch Bowl State Natural Area", Type = "Natural Area", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 159, Name = "Ellmaker State Wayside", Type = "Wayside", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 160, Name = "Fogarty Creek State Recreation Area", Type = "Recreation Area", Camping = false, NearestCity = "Depoe Bay" },
          new Park { ParkId = 161, Name = "Gleneden Beach State Recreation Site", Type = "Recreation Area", Camping = false, NearestCity = "Lincoln City" },
          new Park { ParkId = 162, Name = "H. B. Van Duzer Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Lincoln City" },
          new Park { ParkId = 163, Name = "Neskowin Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Neskowin" },
          new Park { ParkId = 164, Name = "Otter Crest State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 165, Name = "Roads End State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Lincoln City" },
          new Park { ParkId = 166, Name = "Beverly Beach State Park", Type = "State Park", Camping = true, NearestCity = "Newport" },
          new Park { ParkId = 167, Name = "Collier Memorial State Park", Type = "State Park", Camping = true, NearestCity = "Klamath Falls" },
          new Park { ParkId = 168, Name = "Jackson F. Kimball State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "Fort Klamath" },
          new Park { ParkId = 169, Name = "OC&E Woods Line State Trail", Type = "State Trail", Camping = false, NearestCity = "Klamath Falls" },
          new Park { ParkId = 170, Name = "South Jetty (South Beach)", Type = "Beach Access", Camping = false, NearestCity = "Newport" },
          new Park { ParkId = 171, Name = "Blue Mountain Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "La Grande" },
          new Park { ParkId = 172, Name = "Battle Mountain Forest State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Ukiah" },
          new Park { ParkId = 173, Name = "Sumpter Valley Dredge State Heritage Area", Type = "Heritage Area", Camping = false, NearestCity = "Baker City" },
          new Park { ParkId = 174, Name = "Fall Creek State Recreation Site", Type = "Recreation Site", Camping = true, NearestCity = "Springfield" },
          new Park { ParkId = 175, Name = "Lowell State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Springfield" },
          new Park { ParkId = 176, Name = "Jasper State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Springfield" },
          new Park { ParkId = 177, Name = "Dexter State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Springfield" },
          new Park { ParkId = 178, Name = "Munson Creek Falls State Natural Site", Type = "Natural Site", Camping = false, NearestCity = "Tillamook" },
          new Park { ParkId = 179, Name = "Willamette Stone State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Portland" },
          new Park { ParkId = 180, Name = "Umpqua State Scenic Corridor", Type = "Scenic Corridor", Camping = false, NearestCity = "Reedsport" },
          new Park { ParkId = 181, Name = "Clay Myers State Natural Area at Whalen Island", Type = "Natural Area", Camping = false, NearestCity = "Pacific City" },
          new Park { ParkId = 182, Name = "Fort Rock Cave (Near Fort Rock State Natural Area)", Type = "National Historic Landmark", Camping = false, NearestCity = "Fort Rock" },
          new Park { ParkId = 183, Name = "Government Island State Recreation Area", Type = "Recreation Area", Camping = true, NearestCity = "Portland" },
          new Park { ParkId = 184, Name = "Sunset Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Astoria" },
          new Park { ParkId = 185, Name = "Whale Watching Center", Type = "Guided Ocean Viewpoint", Camping = false, NearestCity = "Depoe Bay" },
          new Park { ParkId = 186, Name = "Rocky Creek State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Depoe Bay" },
          new Park { ParkId = 187, Name = "Fort Yamhill State Heritage Area", Type = "Heritage Area", Camping = false, NearestCity = "Grand Ronde" },
          new Park { ParkId = 188, Name = "L. L. 'Stub' Stewart State Park", Type = "State Park", Camping = true, NearestCity = "Vernonia" },
          new Park { ParkId = 189, Name = "Thompson's Mills State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "Shedd" },
          new Park { ParkId = 190, Name = "State Capitol State Park", Type = "State Park", Camping = false, NearestCity = "Salem" },
          new Park { ParkId = 191, Name = "Arizona Beach State Recreation Site", Type = "Recreation Site", Camping = false, NearestCity = "Port Orford" },
          new Park { ParkId = 192, Name = "Bates State Park", Type = "State Park", Camping = false, NearestCity = "Prairie City" },
          new Park { ParkId = 193, Name = "Ochoco State Scenic Viewpoint", Type = "Scenic Viewpoint", Camping = false, NearestCity = "Prineville" },
          new Park { ParkId = 194, Name = "Dyer State Wayside", Type = "Wayside", Camping = false, NearestCity = "Condon" },
          new Park { ParkId = 195, Name = "Pete French Round Barn State Heritage Site", Type = "Heritage Site", Camping = false, NearestCity = "New Princeton" },
          new Park { ParkId = 196, Name = "Cottonwood Canyon State Park", Type = "State Park", Camping = false, NearestCity = "Moro" }
        );

        builder.Entity<Region>()
          .HasData(
            new Region { RegionId =1, Name = "Southern Oregon"},
            new Region { RegionId =2, Name = "Eastern Oregon"},
            new Region { RegionId =3, Name = "Central Oregon"},
            new Region { RegionId =4, Name = "Portland/Columbia Gorge"},
            new Region { RegionId =5, Name = "South Coast"},
            new Region { RegionId =6, Name = "Willamette Valley"},
            new Region { RegionId =7, Name = "Central Coast"},
            new Region { RegionId =8, Name = "North Coast"}
          );

        builder.Entity<ParkRegion>()
          .HasData(
            new ParkRegion { ParkRegionId =1, ParkId =1, RegionId =1 },
            new ParkRegion { ParkRegionId =2, ParkId =22, RegionId =1 },
            new ParkRegion { ParkRegionId =3, ParkId =23, RegionId =1 },
            new ParkRegion { ParkRegionId =4, ParkId =24, RegionId =1 },
            new ParkRegion { ParkRegionId =5, ParkId =38, RegionId =1 },
            new ParkRegion { ParkRegionId =6, ParkId =39, RegionId =1 },
            new ParkRegion { ParkRegionId =7, ParkId =71, RegionId =1 },
            new ParkRegion { ParkRegionId =8, ParkId =72, RegionId =1 },
            new ParkRegion { ParkRegionId =9, ParkId =73, RegionId =1 },
            new ParkRegion { ParkRegionId =10, ParkId =74, RegionId =1 },
            new ParkRegion { ParkRegionId =11, ParkId =75, RegionId =1 },
            new ParkRegion { ParkRegionId =12, ParkId =138, RegionId =1 },
            new ParkRegion { ParkRegionId =13, ParkId =167, RegionId =1 },
            new ParkRegion { ParkRegionId =14, ParkId =168, RegionId =1 },
            new ParkRegion { ParkRegionId =15, ParkId =169, RegionId =1 },
            new ParkRegion { ParkRegionId =16, ParkId =2, RegionId =2 },
            new ParkRegion { ParkRegionId =17, ParkId =3, RegionId =2 },
            new ParkRegion { ParkRegionId =18, ParkId =4, RegionId =2 },
            new ParkRegion { ParkRegionId =19, ParkId =5, RegionId =2 },
            new ParkRegion { ParkRegionId =20, ParkId =6, RegionId =2 },
            new ParkRegion { ParkRegionId =21, ParkId =7, RegionId =2 },
            new ParkRegion { ParkRegionId =22, ParkId =8, RegionId =2 },
            new ParkRegion { ParkRegionId =23, ParkId =9, RegionId =2 },
            new ParkRegion { ParkRegionId =24, ParkId =10, RegionId =2 },
            new ParkRegion { ParkRegionId =25, ParkId =11, RegionId =2 },
            new ParkRegion { ParkRegionId =26, ParkId =12, RegionId =2 },
            new ParkRegion { ParkRegionId =27, ParkId =13, RegionId =2 },
            new ParkRegion { ParkRegionId =28, ParkId =14, RegionId =2 },
            new ParkRegion { ParkRegionId =29, ParkId =15, RegionId =2 },
            new ParkRegion { ParkRegionId =30, ParkId =16, RegionId =2 },
            new ParkRegion { ParkRegionId =31, ParkId =17, RegionId =2 },
            new ParkRegion { ParkRegionId =32, ParkId =18, RegionId =2 },
            new ParkRegion { ParkRegionId =33, ParkId =19, RegionId =2 },
            new ParkRegion { ParkRegionId =34, ParkId =20, RegionId =2 },
            new ParkRegion { ParkRegionId =35, ParkId =21, RegionId =2 },
            new ParkRegion { ParkRegionId =36, ParkId =171, RegionId =2 },
            new ParkRegion { ParkRegionId =37, ParkId =172, RegionId =2 },
            new ParkRegion { ParkRegionId =38, ParkId =173, RegionId =2 },
            new ParkRegion { ParkRegionId =39, ParkId =192, RegionId =2 },
            new ParkRegion { ParkRegionId =40, ParkId =194, RegionId =2 },
            new ParkRegion { ParkRegionId =41, ParkId =195, RegionId =2 },
            new ParkRegion { ParkRegionId =42, ParkId =25, RegionId =3 },
            new ParkRegion { ParkRegionId =43, ParkId =26, RegionId =3 },
            new ParkRegion { ParkRegionId =44, ParkId =27, RegionId =3 },
            new ParkRegion { ParkRegionId =45, ParkId =31, RegionId =3 },
            new ParkRegion { ParkRegionId =46, ParkId =32, RegionId =3 },
            new ParkRegion { ParkRegionId =47, ParkId =33, RegionId =3 },
            new ParkRegion { ParkRegionId =48, ParkId =34, RegionId =3 },
            new ParkRegion { ParkRegionId =49, ParkId =35, RegionId =3 },
            new ParkRegion { ParkRegionId =50, ParkId =36, RegionId =3 },
            new ParkRegion { ParkRegionId =51, ParkId =37, RegionId =3 },
            new ParkRegion { ParkRegionId =52, ParkId =182, RegionId =3 },
            new ParkRegion { ParkRegionId =53, ParkId =193, RegionId =3 },
            new ParkRegion { ParkRegionId =54, ParkId =196, RegionId =3 },
            new ParkRegion { ParkRegionId =55, ParkId =28, RegionId =4 },
            new ParkRegion { ParkRegionId =56, ParkId =29, RegionId =4 },
            new ParkRegion { ParkRegionId =57, ParkId =30, RegionId =4 },
            new ParkRegion { ParkRegionId =58, ParkId =76, RegionId =4 },
            new ParkRegion { ParkRegionId =59, ParkId =77, RegionId =4 },
            new ParkRegion { ParkRegionId =60, ParkId =101, RegionId =4 },
            new ParkRegion { ParkRegionId =61, ParkId =102, RegionId =4 },
            new ParkRegion { ParkRegionId =62, ParkId =103, RegionId =4 },
            new ParkRegion { ParkRegionId =63, ParkId =104, RegionId =4 },
            new ParkRegion { ParkRegionId =64, ParkId =105, RegionId =4 },
            new ParkRegion { ParkRegionId =65, ParkId =106, RegionId =4 },
            new ParkRegion { ParkRegionId =66, ParkId =107, RegionId =4 },
            new ParkRegion { ParkRegionId =67, ParkId =108, RegionId =4 },
            new ParkRegion { ParkRegionId =68, ParkId =109, RegionId =4 },
            new ParkRegion { ParkRegionId =69, ParkId =110, RegionId =4 },
            new ParkRegion { ParkRegionId =70, ParkId =111, RegionId =4 },
            new ParkRegion { ParkRegionId =71, ParkId =112, RegionId =4 },
            new ParkRegion { ParkRegionId =72, ParkId =113, RegionId =4 },
            new ParkRegion { ParkRegionId =73, ParkId =114, RegionId =4 },
            new ParkRegion { ParkRegionId =74, ParkId =115, RegionId =4 },
            new ParkRegion { ParkRegionId =75, ParkId =116, RegionId =4 },
            new ParkRegion { ParkRegionId =76, ParkId =117, RegionId =4 },
            new ParkRegion { ParkRegionId =77, ParkId =118, RegionId =4 },
            new ParkRegion { ParkRegionId =78, ParkId =119, RegionId =4 },
            new ParkRegion { ParkRegionId =79, ParkId =120, RegionId =4 },
            new ParkRegion { ParkRegionId =80, ParkId =121, RegionId =4 },
            new ParkRegion { ParkRegionId =81, ParkId =122, RegionId =4 },
            new ParkRegion { ParkRegionId =82, ParkId =123, RegionId =4 },
            new ParkRegion { ParkRegionId =83, ParkId =124, RegionId =4 },
            new ParkRegion { ParkRegionId =84, ParkId =125, RegionId =4 },
            new ParkRegion { ParkRegionId =85, ParkId =126, RegionId =4 },
            new ParkRegion { ParkRegionId =86, ParkId =127, RegionId =4 },
            new ParkRegion { ParkRegionId =87, ParkId =179, RegionId =4 },
            new ParkRegion { ParkRegionId =88, ParkId =183, RegionId =4 },
            new ParkRegion { ParkRegionId =89, ParkId =188, RegionId =4 },
            new ParkRegion { ParkRegionId =90, ParkId =40, RegionId =5 },
            new ParkRegion { ParkRegionId =91, ParkId =41, RegionId =5 },
            new ParkRegion { ParkRegionId =92, ParkId =42, RegionId =5 },
            new ParkRegion { ParkRegionId =93, ParkId =43, RegionId =5 },
            new ParkRegion { ParkRegionId =94, ParkId =44, RegionId =5 },
            new ParkRegion { ParkRegionId =95, ParkId =45, RegionId =5 },
            new ParkRegion { ParkRegionId =96, ParkId =46, RegionId =5 },
            new ParkRegion { ParkRegionId =97, ParkId =47, RegionId =5 },
            new ParkRegion { ParkRegionId =98, ParkId =48, RegionId =5 },
            new ParkRegion { ParkRegionId =99, ParkId =49, RegionId =5 },
            new ParkRegion { ParkRegionId =100, ParkId =50, RegionId =5 },
            new ParkRegion { ParkRegionId =101, ParkId =51, RegionId =5 },
            new ParkRegion { ParkRegionId =102, ParkId =52, RegionId =5 },
            new ParkRegion { ParkRegionId =103, ParkId =53, RegionId =5 },
            new ParkRegion { ParkRegionId =104, ParkId =54, RegionId =5 },
            new ParkRegion { ParkRegionId =105, ParkId =55, RegionId =5 },
            new ParkRegion { ParkRegionId =106, ParkId =56, RegionId =5 },
            new ParkRegion { ParkRegionId =107, ParkId =57, RegionId =5 },
            new ParkRegion { ParkRegionId =108, ParkId =58, RegionId =5 },
            new ParkRegion { ParkRegionId =109, ParkId =59, RegionId =5 },
            new ParkRegion { ParkRegionId =110, ParkId =66, RegionId =5 },
            new ParkRegion { ParkRegionId =111, ParkId =67, RegionId =5 },
            new ParkRegion { ParkRegionId =112, ParkId =68, RegionId =5 },
            new ParkRegion { ParkRegionId =113, ParkId =69, RegionId =5 },
            new ParkRegion { ParkRegionId =114, ParkId =70, RegionId =5 },
            new ParkRegion { ParkRegionId =115, ParkId =180, RegionId =5 },
            new ParkRegion { ParkRegionId =116, ParkId =191, RegionId =5 },
            new ParkRegion { ParkRegionId =117, ParkId =60, RegionId =6 },
            new ParkRegion { ParkRegionId =118, ParkId =61, RegionId =6 },
            new ParkRegion { ParkRegionId =119, ParkId =62, RegionId =6 },
            new ParkRegion { ParkRegionId =120, ParkId =63, RegionId =6 },
            new ParkRegion { ParkRegionId =121, ParkId =64, RegionId =6 },
            new ParkRegion { ParkRegionId =122, ParkId =65, RegionId =6 },
            new ParkRegion { ParkRegionId =123, ParkId =78, RegionId =6 },
            new ParkRegion { ParkRegionId =124, ParkId =96, RegionId =6 },
            new ParkRegion { ParkRegionId =125, ParkId =97, RegionId =6 },
            new ParkRegion { ParkRegionId =126, ParkId =98, RegionId =6 },
            new ParkRegion { ParkRegionId =127, ParkId =99, RegionId =6 },
            new ParkRegion { ParkRegionId =128, ParkId =100, RegionId =6 },
            new ParkRegion { ParkRegionId =129, ParkId =152, RegionId =6 },
            new ParkRegion { ParkRegionId =130, ParkId =153, RegionId =6 },
            new ParkRegion { ParkRegionId =131, ParkId =174, RegionId =6 },
            new ParkRegion { ParkRegionId =132, ParkId =175, RegionId =6 },
            new ParkRegion { ParkRegionId =133, ParkId =176, RegionId =6 },
            new ParkRegion { ParkRegionId =134, ParkId =177, RegionId =6 },
            new ParkRegion { ParkRegionId =135, ParkId =187, RegionId =6 },
            new ParkRegion { ParkRegionId =136, ParkId =189, RegionId =6 },
            new ParkRegion { ParkRegionId =137, ParkId =190, RegionId =6 },
            new ParkRegion { ParkRegionId =138, ParkId =79, RegionId =7 },
            new ParkRegion { ParkRegionId =139, ParkId =80, RegionId =7 },
            new ParkRegion { ParkRegionId =140, ParkId =81, RegionId =7 },
            new ParkRegion { ParkRegionId =141, ParkId =82, RegionId =7 },
            new ParkRegion { ParkRegionId =142, ParkId =83, RegionId =7 },
            new ParkRegion { ParkRegionId =143, ParkId =84, RegionId =7 },
            new ParkRegion { ParkRegionId =144, ParkId =85, RegionId =7 },
            new ParkRegion { ParkRegionId =145, ParkId =86, RegionId =7 },
            new ParkRegion { ParkRegionId =146, ParkId =87, RegionId =7 },
            new ParkRegion { ParkRegionId =147, ParkId =88, RegionId =7 },
            new ParkRegion { ParkRegionId =148, ParkId =89, RegionId =7 },
            new ParkRegion { ParkRegionId =149, ParkId =90, RegionId =7 },
            new ParkRegion { ParkRegionId =150, ParkId =91, RegionId =7 },
            new ParkRegion { ParkRegionId =151, ParkId =92, RegionId =7 },
            new ParkRegion { ParkRegionId =152, ParkId =93, RegionId =7 },
            new ParkRegion { ParkRegionId =153, ParkId =94, RegionId =7 },
            new ParkRegion { ParkRegionId =154, ParkId =95, RegionId =7 },
            new ParkRegion { ParkRegionId =155, ParkId =145, RegionId =7 },
            new ParkRegion { ParkRegionId =156, ParkId =146, RegionId =7 },
            new ParkRegion { ParkRegionId =157, ParkId =147, RegionId =7 },
            new ParkRegion { ParkRegionId =158, ParkId =148, RegionId =7 },
            new ParkRegion { ParkRegionId =159, ParkId =149, RegionId =7 },
            new ParkRegion { ParkRegionId =160, ParkId =150, RegionId =7 },
            new ParkRegion { ParkRegionId =161, ParkId =151, RegionId =7 },
            new ParkRegion { ParkRegionId =162, ParkId =154, RegionId =7 },
            new ParkRegion { ParkRegionId =163, ParkId =155, RegionId =7 },
            new ParkRegion { ParkRegionId =164, ParkId =158, RegionId =7 },
            new ParkRegion { ParkRegionId =165, ParkId =159, RegionId =7 },
            new ParkRegion { ParkRegionId =166, ParkId =160, RegionId =7 },
            new ParkRegion { ParkRegionId =167, ParkId =161, RegionId =7 },
            new ParkRegion { ParkRegionId =168, ParkId =164, RegionId =7 },
            new ParkRegion { ParkRegionId =169, ParkId =166, RegionId =7 },
            new ParkRegion { ParkRegionId =170, ParkId =170, RegionId =7 },
            new ParkRegion { ParkRegionId =171, ParkId =185, RegionId =7 },
            new ParkRegion { ParkRegionId =172, ParkId =186, RegionId =7 },
            new ParkRegion { ParkRegionId =173, ParkId =128, RegionId =8 },
            new ParkRegion { ParkRegionId =174, ParkId =129, RegionId =8 },
            new ParkRegion { ParkRegionId =175, ParkId =130, RegionId =8 },
            new ParkRegion { ParkRegionId =176, ParkId =131, RegionId =8 },
            new ParkRegion { ParkRegionId =177, ParkId =132, RegionId =8 },
            new ParkRegion { ParkRegionId =178, ParkId =133, RegionId =8 },
            new ParkRegion { ParkRegionId =179, ParkId =134, RegionId =8 },
            new ParkRegion { ParkRegionId =180, ParkId =135, RegionId =8 },
            new ParkRegion { ParkRegionId =181, ParkId =136, RegionId =8 },
            new ParkRegion { ParkRegionId =182, ParkId =137, RegionId =8 },
            new ParkRegion { ParkRegionId =183, ParkId =139, RegionId =8 },
            new ParkRegion { ParkRegionId =184, ParkId =140, RegionId =8 },
            new ParkRegion { ParkRegionId =185, ParkId =141, RegionId =8 },
            new ParkRegion { ParkRegionId =186, ParkId =142, RegionId =8 },
            new ParkRegion { ParkRegionId =187, ParkId =143, RegionId =8 },
            new ParkRegion { ParkRegionId =188, ParkId =144, RegionId =8 },
            new ParkRegion { ParkRegionId =189, ParkId =156, RegionId =8 },
            new ParkRegion { ParkRegionId =190, ParkId =157, RegionId =8 },
            new ParkRegion { ParkRegionId =191, ParkId =162, RegionId =8 },
            new ParkRegion { ParkRegionId =192, ParkId =163, RegionId =8 },
            new ParkRegion { ParkRegionId =193, ParkId =165, RegionId =8 },
            new ParkRegion { ParkRegionId =194, ParkId =178, RegionId =8 },
            new ParkRegion { ParkRegionId =195, ParkId =181, RegionId =8 },
            new ParkRegion { ParkRegionId =196, ParkId =184, RegionId =8 },
            new ParkRegion { ParkRegionId =197, ParkId =197, RegionId =8 }
          );
      }
    }
}