using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace StatePark.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Parks",
                columns: table => new
                {
                    ParkId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "longtext CHARACTER SET utf8mb4", nullable: true),
                    Type = table.Column<string>(type: "longtext CHARACTER SET utf8mb4", nullable: true),
                    Camping = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    NearestCity = table.Column<string>(type: "longtext CHARACTER SET utf8mb4", nullable: true),
                    RegionId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Parks", x => x.ParkId);
                });

            migrationBuilder.CreateTable(
                name: "Regions",
                columns: table => new
                {
                    RegionId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "longtext CHARACTER SET utf8mb4", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Regions", x => x.RegionId);
                });

            migrationBuilder.InsertData(
                table: "Parks",
                columns: new[] { "ParkId", "Camping", "Name", "NearestCity", "RegionId", "Type" },
                values: new object[,]
                {
                    { 1, true, "Goose Lake State Recreation Area", "NearestCity", 1, "Recreation Area" },
                    { 128, false, "Bradley State Scenic Viewpoint", "Multnomah Falls", 8, "Scenic Viewpoint" },
                    { 129, false, "Del Rey Beach State Recreation Site", "Astoria", 8, "Recreation Site" },
                    { 130, true, "Fort Stevens State Park", "Gearhart", 8, "State Park" },
                    { 131, false, "Cape Kiwanda State Natural Area", "Astoria", 8, "Natural Area" },
                    { 132, false, "Cape Meares State Scenic Viewpoint", "Pacific City", 8, "Scenic Viewpoint" },
                    { 133, false, "Oceanside Beach State Recreation Site", "Tillamook", 8, "Recreation Site" },
                    { 134, false, "Bob Straub State Park", "Tillamook", 8, "State Park" },
                    { 135, true, "Cape Lookout State Park", "Pacific City", 8, "State Park" },
                    { 136, false, "Arcadia Beach State Recreation Site", "Tillamook", 8, "Recreation Site" },
                    { 127, false, "Rooster Rock State Park", "Hood River", 4, "State Park" },
                    { 137, false, "Ecola State Park", "Cannon Beach", 8, "State Park" },
                    { 139, false, "Hug Point State Recreation Site", "Grants Pass", 8, "Recreation Site" },
                    { 140, false, "Manhattan Beach State Recreation Site", "Cannon Beach", 8, "Recreation Site" },
                    { 141, false, "Oswald West State Park", "Rockaway Beach", 8, "State Park" },
                    { 142, true, "Saddle Mountain State Natural Area", "Cannon Beach", 8, "Natural Area" },
                    { 143, false, "Tolovana Beach State Recreation Site", "Seaside", 8, "Recreation Site" },
                    { 144, true, "Nehalem Bay State Park", "Cannon Beach", 8, "State Park" },
                    { 145, false, "Alsea Bay Historic Interpretive Center", "Manzanita", 7, "Interpretive Center" },
                    { 146, false, "Driftwood Beach State Recreation Site", "Waldport", 7, "Recreation Site" },
                    { 147, false, "Lost Creek State Recreation Site", "Waldport", 7, "Recreation Site" },
                    { 138, false, "Golden State Heritage Site", "Cannon Beach", 1, "Heritage Site" },
                    { 126, false, "Wygant State Natural Area", "Hood River", 4, "Natural Area" },
                    { 125, false, "Vinzenz Lausmann Memorial State Natural Area", "Hood River", 4, "Natural Area" },
                    { 124, true, "Viento State Park", "Hood River", 4, "State Park" },
                    { 102, false, "Mary S. Young State Recreation Area", "Estacada", 4, "Recreation Area" },
                    { 104, false, "Tryon Creek State Natural Area", "Estacada", 4, "Natural Area" },
                    { 105, false, "Banks–Vernonia State Trail", "Portland", 4, "State Trail" },
                    { 106, true, "Ainsworth State Park", "Vernonia", 4, "State Park" },
                    { 107, false, "Benson State Recreation Area", "Multnomah Falls", 4, "Recreation Area" },
                    { 108, false, "Bridal Veil Falls State Scenic Viewpoint", "Multnomah Falls", 4, "Scenic Viewpoint" },
                    { 109, false, "Crown Point State Scenic Corridor", "Multnomah Falls", 4, "Scenic Corridor" },
                    { 110, false, "Dabney State Recreation Area", "Troutdale", 4, "Recreation Area" },
                    { 111, false, "George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)", "Troutdale", 4, "Natural Area" },
                    { 112, false, "Guy W. Talbot State Park", "Troutdale", 4, "State Park" },
                    { 113, false, "Historic Columbia River Highway State Trail", "Troutdale", 4, "State Trail" },
                    { 114, false, "John B. Yeon State Scenic Corridor", "Cascade Locks", 4, "Scenic Corridor" },
                    { 115, false, "Koberg Beach State Recreation Site", "Cascade Locks", 4, "Recreation Site" },
                    { 116, false, "Lewis and Clark State Recreation Site", "Hood River", 4, "Recreation Site" },
                    { 117, false, "Mayer State Park", "Troutdale", 4, "State Park" },
                    { 118, true, "Memaloose State Park", "The Dalles", 4, "State Park" },
                    { 119, false, "Portland Women's Forum State Scenic Viewpoint", "The Dalles", 4, "Scenic Viewpoint" },
                    { 120, false, "Seneca Fouts Memorial State Natural Area", "Troutdale", 4, "Natural Area" },
                    { 121, false, "Shepperd's Dell State Natural Area", "Hood River", 4, "Natural Area" },
                    { 122, false, "Sheridan State Scenic Corridor", "Multnomah Falls", 4, "Scenic Corridor" },
                    { 123, false, "Starvation Creek State Park", "Cascade Locks", 4, "State Park" },
                    { 148, false, "Ona Beach State Park", "Newport", 7, "State Park" },
                    { 149, false, "Seal Rock State Recreation Site", "Newport", 7, "Recreation Site" },
                    { 150, false, "Yaquina Bay State Recreation Site", "Newport", 7, "Recreation Site" },
                    { 151, true, "South Beach State Park", "Newport", 7, "State Park" },
                    { 177, false, "Dexter State Recreation Site", "Springfield", 6, "Recreation Site" },
                    { 178, false, "Munson Creek Falls State Natural Site", "Springfield", 8, "Natural Site" },
                    { 179, false, "Willamette Stone State Heritage Site", "Tillamook", 4, "Heritage Site" },
                    { 180, false, "Umpqua State Scenic Corridor", "Portland", 5, "Scenic Corridor" },
                    { 181, false, "Clay Myers State Natural Area at Whalen Island", "Reedsport", 8, "Natural Area" },
                    { 182, false, "Fort Rock Cave (Near Fort Rock State Natural Area)", "Pacific City", 3, "National Historic Landmark" },
                    { 183, true, "Government Island State Recreation Area", "Fort Rock", 4, "Recreation Area" },
                    { 184, false, "Sunset Beach State Recreation Site", "Portland", 8, "Recreation Site" },
                    { 185, false, "Whale Watching Center", "Astoria", 7, "Guided Ocean Viewpoint" },
                    { 186, false, "Rocky Creek State Scenic Viewpoint", "Depoe Bay", 7, "Scenic Viewpoint" },
                    { 187, false, "Fort Yamhill State Heritage Area", "Depoe Bay", 6, "Heritage Area" },
                    { 188, true, "L. L. 'Stub' Stewart State Park", "Grand Ronde", 4, "State Park" },
                    { 189, false, "Thompson's Mills State Heritage Site", "Vernonia", 6, "Heritage Site" },
                    { 190, false, "State Capitol State Park", "Shedd", 6, "State Park" },
                    { 191, false, "Arizona Beach State Recreation Site", "Salem", 5, "Recreation Site" },
                    { 192, false, "Bates State Park", "Port Orford", 2, "State Park" },
                    { 193, false, "Ochoco State Scenic Viewpoint", "Prairie City", 3, "Scenic Viewpoint" },
                    { 194, false, "Dyer State Wayside", "Prineville", 2, "Wayside" },
                    { 195, false, "Pete French Round Barn State Heritage Site", "Condon", 2, "Heritage Site" },
                    { 196, false, "Cottonwood Canyon State Park", "New Princeton", 3, "State Park" },
                    { 197, false, "Sitka Sedge State Natural Area", "Moro", 8, "Natural Site" },
                    { 176, false, "Jasper State Recreation Site", "Springfield", 6, "Recreation Site" },
                    { 101, false, "Bonnie Lure State Recreation Area", "Salem", 4, "Recreation Area" },
                    { 175, false, "Lowell State Recreation Site", "Springfield", 6, "Recreation Site" },
                    { 173, false, "Sumpter Valley Dredge State Heritage Area", "Ukiah", 2, "Heritage Area" },
                    { 152, true, "Cascadia State Park", "Newport", 6, "State Park" },
                    { 153, true, "Silver Falls State Park", "Sweet Home", 6, "State Park" },
                    { 154, false, "Agate Beach State Recreation Site", "Silverton", 7, "Recreation Site" },
                    { 155, false, "Boiler Bay State Scenic Viewpoint", "Newport", 7, "Scenic Viewpoint" },
                    { 156, false, "D River State Recreation Site", "Depoe Bay", 8, "Recreation Site" },
                    { 157, true, "Devils Lake State Recreation Area", "Lincoln City", 8, "Recreation Area" },
                    { 158, false, "Devils Punch Bowl State Natural Area", "Lincoln City", 7, "Natural Area" },
                    { 159, false, "Ellmaker State Wayside", "Newport", 7, "Wayside" },
                    { 160, false, "Fogarty Creek State Recreation Area", "Newport", 7, "Recreation Area" },
                    { 161, false, "Gleneden Beach State Recreation Site", "Depoe Bay", 7, "Recreation Area" },
                    { 162, false, "H. B. Van Duzer Forest State Scenic Corridor", "Lincoln City", 8, "Scenic Corridor" },
                    { 163, false, "Neskowin Beach State Recreation Site", "Lincoln City", 8, "Recreation Site" },
                    { 164, false, "Otter Crest State Scenic Viewpoint", "Neskowin", 7, "Scenic Viewpoint" },
                    { 165, false, "Roads End State Recreation Site", "Newport", 8, "Recreation Site" },
                    { 166, true, "Beverly Beach State Park", "Lincoln City", 7, "State Park" },
                    { 167, true, "Collier Memorial State Park", "Newport", 1, "State Park" },
                    { 168, true, "Jackson F. Kimball State Recreation Site", "Klamath Falls", 1, "Recreation Site" },
                    { 169, false, "OC&E Woods Line State Trail", "Fort Klamath", 1, "State Trail" },
                    { 170, false, "South Jetty (South Beach)", "Klamath Falls", 7, "Beach Access" },
                    { 171, false, "Blue Mountain Forest State Scenic Corridor", "Newport", 2, "Scenic Corridor" },
                    { 172, false, "Battle Mountain Forest State Scenic Corridor", "La Grande", 2, "Scenic Corridor" },
                    { 174, true, "Fall Creek State Recreation Site", "Baker City", 6, "Recreation Site" },
                    { 100, false, "Willamette Mission State Park", "Monmouth", 6, "State Park" },
                    { 103, true, "Milo McIver State Park", "West Linn", 4, "State Park" },
                    { 98, false, "Maud Williamson State Recreation Site", "Salem", 6, "Recreation Site" },
                    { 27, true, "Prineville Reservoir State Park", "Prineville", 3, "State Park" },
                    { 28, false, "Heritage Landing (Deschutes)", "Prineville", 4, "Boat Launch" },
                    { 29, false, "White River Falls State Park", "The Dalles", 4, "State Park" },
                    { 30, true, "Deschutes River State Recreation Area", "The Dalles", 4, "Recreation Area" },
                    { 31, false, "Cline Falls State Scenic Viewpoint", "The Dalles", 3, "Scenic Viewpoint" },
                    { 32, true, "Fort Rock State Natural Area", "Redmond", 3, "Natural Area" },
                    { 33, true, "La Pine State Park", "Fort Rock", 3, "State Park" },
                    { 34, false, "Pilot Butte State Scenic Viewpoint", "La Pine", 3, "Scenic Viewpoint" },
                    { 35, true, "Tumalo State Park", "Bend", 3, "State Park" },
                    { 36, false, "Peter Skene Ogden State Scenic Viewpoint", "Bend", 3, "Scenic Viewpoint" },
                    { 37, true, "Smith Rock State Park", "Redmond", 3, "State Park" },
                    { 38, false, "Booth State Scenic Corridor", "Redmond", 1, "Scenic Corridor" },
                    { 39, false, "Chandler State Wayside", "Lakeview", 1, "Wayside" },
                    { 40, false, "Geisel Monument State Heritage Site", "Lakeview", 5, "Heritage Site" },
                    { 41, true, "Humbug Mountain State Park", "Gold Beach", 5, "State Park" },
                    { 42, false, "Otter Point State Recreation Site", "Port Orford", 5, "Recreation Site" },
                    { 43, false, "Paradise Point State Recreation Site", "Gold Beach", 5, "Recreation Site" },
                    { 44, false, "Port Orford Heads State Park", "Port Orford", 5, "State Park" },
                    { 45, true, "Cape Blanco State Park", "Port Orford", 5, "State Park" },
                    { 46, false, "Bandon State Natural Area", "Port Orford", 5, "Natural Area" },
                    { 99, false, "Sarah Helmick State Recreation Site", "Salem", 6, "Recreation Site" },
                    { 26, true, "Jasper Point Campground", "Madras", 3, "Campground" },
                    { 48, false, "Face Rock State Scenic Viewpoint", "Myrtle Point", 5, "Scenic Viewpoint" },
                    { 25, true, "The Cove Palisades State Park", "Medford", 3, "State Park" },
                    { 23, false, "Prospect State Scenic Viewpoint", "Medford", 1, "Scenic Viewpoint" },
                    { 2, false, "Frenchglen Hotel State Heritage Site", "Lakeview", 2, "Heritage Site" },
                    { 3, false, "Ontario State Recreation Site", "Burns", 2, "Recreation Site" },
                    { 4, true, "Farewell Bend State Recreation Area", "Ontario", 2, "Recreation Area" },
                    { 5, false, "Kam Wah Chung State Heritage Site", "Ontario", 2, "Heritage Site" },
                    { 6, false, "Unity Forest State Scenic Corridor", "John Day", 2, "Scenic Corridor" },
                    { 7, true, "Unity Lake State Recreation Site", "John Day", 2, "Recreation Site" },
                    { 8, true, "Clyde Holliday State Recreation Site", "John Day", 2, "Recreation Site" },
                    { 9, true, "Succor Creek State Natural Area", "John Day", 2, "Natural Area" },
                    { 10, true, "Lake Owyhee State Park", "Nyssa", 2, "State Park" },
                    { 11, true, "Catherine Creek State Park", "Nyssa", 2, "State Park" },
                    { 12, false, "Hat Rock State Park", "Union", 2, "State Park" },
                    { 13, true, "Hilgard Junction State Recreation Area", "Umatilla", 2, "Recreation Area" },
                    { 14, true, "Red Bridge State Wayside", "La Grande", 2, "Wayside" },
                    { 15, true, "Ukiah–Dale Forest State Scenic Corridor", "La Grande", 2, "Scenic Corridor" },
                    { 16, true, "Emigrant Springs State Heritage Area", "Ukiah", 2, "Heritage Area" },
                    { 17, false, "Wallowa Lake Highway Forest State Scenic Corridor", "Pendleton", 2, "Scenic Corridor" },
                    { 18, false, "Wallowa River Rest Area", "Enterprise", 2, "Rest Area" },
                    { 19, true, "Minam State Recreation Area", "La Grande", 2, "Recreation Area" },
                    { 20, true, "Wallowa Lake State Recreation Area", "Elgin", 2, "Recreation Area" },
                    { 21, false, "Iwetemlaykin State Heritage Site", "Joseph", 2, "Heritage Site" },
                    { 22, false, "Casey State Recreation Site", "Joseph", 1, "Recreation Site" },
                    { 24, true, "Joseph H. Stewart State Recreation Area", "Prospect", 1, "Recreation Area" },
                    { 49, false, "Hoffman Memorial State Wayside", "Bandon", 5, "Wayside" },
                    { 47, false, "Coquille Myrtle Grove State Natural Site", "Bandon", 5, "Natural Site" },
                    { 51, true, "Bullards Beach State Park", "Bandon", 5, "State Park" },
                    { 77, false, "Molalla River State Park", "Newberg", 4, "State Park" },
                    { 50, false, "Seven Devils State Recreation Site", "Myrtle Point", 5, "Recreation Site" },
                    { 79, false, "Beaver Creek State Natural Area", "Newberg", 7, "State Park" },
                    { 80, false, "Bolon Island Tideways State Scenic Corridor", "Newport", 7, "Scenic Corridor" },
                    { 81, false, "Darlingtonia State Natural Site", "Reedsport", 7, "Natural Site" },
                    { 82, false, "Governor Patterson Memorial State Recreation Site", "Florence", 7, "Recreation Site" },
                    { 83, true, "Umpqua Lighthouse State Park", "Waldport", 7, "State Park" },
                    { 84, true, "Beachside State Recreation Site", "Reedsport", 7, "Recreation Site" },
                    { 85, true, "Carl G. Washburne Memorial State Park", "Waldport", 7, "State Park" },
                    { 86, false, "Heceta Head Lighthouse State Scenic Viewpoint", "Florence", 7, "Scenic Viewpoint" },
                    { 87, false, "Muriel O. Ponsler Memorial State Scenic Viewpoint", "Florence", 7, "Scenic Viewpoint" },
                    { 88, false, "Neptune State Scenic Viewpoint", "Florence", 7, "Scenic Viewpoint" },
                    { 89, false, "Smelt Sands State Recreation Site", "Yachats", 7, "Recreation Site" },
                    { 90, false, "Tokatee Klootchman State Natural Site", "Yachats", 7, "Natural Site" },
                    { 91, false, "Stonefield Beach State Recreation Site", "Florence", 7, "Recreation Site" },
                    { 92, false, "W. B. Nelson State Recreation Site", "Yachats", 7, "Recreation Site" },
                    { 93, false, "Yachats Ocean Road State Natural Site", "Waldport", 7, "Natural Site" },
                    { 94, false, "Yachats State Recreation Area", "Yachats", 7, "Recreation Area" },
                    { 95, true, "Jessie M. Honeyman Memorial State Park", "Yachats", 7, "State Park" },
                    { 96, false, "Erratic Rock State Natural Site", "Florence", 6, "Natural Site" },
                    { 97, false, "Holman State Wayside", "Sheridan", 6, "Wayside" },
                    { 76, false, "Bald Peak State Scenic Viewpoint", "Grants Pass", 4, "Scenic Viewpoint" },
                    { 75, true, "Valley of the Rogue State Recreation Area", "Grants Pass", 1, "Recreation Area" },
                    { 78, true, "Champoeg State Heritage Area", "Canby", 6, "Heritage Area" },
                    { 73, false, "Tub Springs State Wayside", "Medford", 1, "Wayside" },
                    { 52, true, "Alfred A. Loeb State Park", "Bandon", 5, "State Park" },
                    { 53, false, "Cape Sebastian State Scenic Corridor", "Brookings", 5, "Scenic Corridor" },
                    { 54, false, "Crissey Field State Recreation Site", "Gold Beach", 5, "Recreation Site" },
                    { 55, false, "McVay Rock State Recreation Site", "Brookings", 5, "Recreation Site" },
                    { 56, false, "Pistol River State Scenic Viewpoint", "Brookings", 5, "Scenic Viewpoint" },
                    { 57, false, "Samuel H. Boardman State Scenic Corridor", "Gold Beach", 5, "Scenic Corridor" },
                    { 74, false, "Wolf Creek Inn State Heritage Site", "Ashland", 1, "Heritage Site" },
                    { 59, true, "Harris Beach State Recreation Area", "Brookings", 5, "Recreation Area" },
                    { 60, false, "Alderwood State Wayside", "Brookings", 6, "Wayside" },
                    { 61, false, "Elijah Bristow State Park", "Junction City", 6, "State Park" },
                    { 58, false, "Winchuck State Recreation Site", "Brookings", 5, "Recreation Site" },
                    { 63, false, "Mongold Day-Use Area", "Junction City", 6, "Boat Launch" },
                    { 72, false, "TouVelle State Recreation Site", "Cave Junction", 1, "Recreation Site" },
                    { 62, false, "Washburne State Wayside", "Eugene", 6, "Wayside" },
                    { 70, true, "Sunset Bay State Park", "Reedsport", 5, "State Park" },
                    { 69, true, "William M. Tugman State Park", "Coos Bay", 5, "State Park" },
                    { 71, false, "Illinois River Forks State Park", "Coos Bay", 1, "State Park" },
                    { 67, false, "Golden and Silver Falls State Natural Area", "Coos Bay", 5, "Natural Area" },
                    { 66, false, "Cape Arago State Park", "Detroit", 5, "State Park" },
                    { 65, true, "Detroit Lake State Recreation Area", "Mill City", 6, "Recreation Area" },
                    { 64, false, "North Santiam State Recreation Area", "Detroit", 6, "Recreation Area" },
                    { 68, false, "Shore Acres State Park", "Coos Bay", 5, "State Park" }
                });

            migrationBuilder.InsertData(
                table: "Regions",
                columns: new[] { "RegionId", "Name" },
                values: new object[,]
                {
                    { 7, "Central Coast" },
                    { 1, "Southern Oregon" },
                    { 2, "Eastern Oregon" },
                    { 3, "Central Oregon" },
                    { 4, "Portland/Columbia Gorge" },
                    { 5, "South Coast" },
                    { 6, "Willamette Valley" },
                    { 8, "North Coast" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Parks");

            migrationBuilder.DropTable(
                name: "Regions");
        }
    }
}
