// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatePark.Models;

namespace StatePark.Migrations
{
    [DbContext(typeof(StateParkContext))]
    partial class StateParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("StatePark.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Camping")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NearestCity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Camping = true,
                            Name = "Goose Lake State Recreation Area",
                            NearestCity = "NearestCity",
                            RegionId = 1,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 2,
                            Camping = false,
                            Name = "Frenchglen Hotel State Heritage Site",
                            NearestCity = "Lakeview",
                            RegionId = 2,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 3,
                            Camping = false,
                            Name = "Ontario State Recreation Site",
                            NearestCity = "Burns",
                            RegionId = 2,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 4,
                            Camping = true,
                            Name = "Farewell Bend State Recreation Area",
                            NearestCity = "Ontario",
                            RegionId = 2,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 5,
                            Camping = false,
                            Name = "Kam Wah Chung State Heritage Site",
                            NearestCity = "Ontario",
                            RegionId = 2,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 6,
                            Camping = false,
                            Name = "Unity Forest State Scenic Corridor",
                            NearestCity = "John Day",
                            RegionId = 2,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 7,
                            Camping = true,
                            Name = "Unity Lake State Recreation Site",
                            NearestCity = "John Day",
                            RegionId = 2,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 8,
                            Camping = true,
                            Name = "Clyde Holliday State Recreation Site",
                            NearestCity = "John Day",
                            RegionId = 2,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 9,
                            Camping = true,
                            Name = "Succor Creek State Natural Area",
                            NearestCity = "John Day",
                            RegionId = 2,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 10,
                            Camping = true,
                            Name = "Lake Owyhee State Park",
                            NearestCity = "Nyssa",
                            RegionId = 2,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 11,
                            Camping = true,
                            Name = "Catherine Creek State Park",
                            NearestCity = "Nyssa",
                            RegionId = 2,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 12,
                            Camping = false,
                            Name = "Hat Rock State Park",
                            NearestCity = "Union",
                            RegionId = 2,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 13,
                            Camping = true,
                            Name = "Hilgard Junction State Recreation Area",
                            NearestCity = "Umatilla",
                            RegionId = 2,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 14,
                            Camping = true,
                            Name = "Red Bridge State Wayside",
                            NearestCity = "La Grande",
                            RegionId = 2,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 15,
                            Camping = true,
                            Name = "Ukiah–Dale Forest State Scenic Corridor",
                            NearestCity = "La Grande",
                            RegionId = 2,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 16,
                            Camping = true,
                            Name = "Emigrant Springs State Heritage Area",
                            NearestCity = "Ukiah",
                            RegionId = 2,
                            Type = "Heritage Area"
                        },
                        new
                        {
                            ParkId = 17,
                            Camping = false,
                            Name = "Wallowa Lake Highway Forest State Scenic Corridor",
                            NearestCity = "Pendleton",
                            RegionId = 2,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 18,
                            Camping = false,
                            Name = "Wallowa River Rest Area",
                            NearestCity = "Enterprise",
                            RegionId = 2,
                            Type = "Rest Area"
                        },
                        new
                        {
                            ParkId = 19,
                            Camping = true,
                            Name = "Minam State Recreation Area",
                            NearestCity = "La Grande",
                            RegionId = 2,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 20,
                            Camping = true,
                            Name = "Wallowa Lake State Recreation Area",
                            NearestCity = "Elgin",
                            RegionId = 2,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 21,
                            Camping = false,
                            Name = "Iwetemlaykin State Heritage Site",
                            NearestCity = "Joseph",
                            RegionId = 2,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 22,
                            Camping = false,
                            Name = "Casey State Recreation Site",
                            NearestCity = "Joseph",
                            RegionId = 1,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 23,
                            Camping = false,
                            Name = "Prospect State Scenic Viewpoint",
                            NearestCity = "Medford",
                            RegionId = 1,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 24,
                            Camping = true,
                            Name = "Joseph H. Stewart State Recreation Area",
                            NearestCity = "Prospect",
                            RegionId = 1,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 25,
                            Camping = true,
                            Name = "The Cove Palisades State Park",
                            NearestCity = "Medford",
                            RegionId = 3,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 26,
                            Camping = true,
                            Name = "Jasper Point Campground",
                            NearestCity = "Madras",
                            RegionId = 3,
                            Type = "Campground"
                        },
                        new
                        {
                            ParkId = 27,
                            Camping = true,
                            Name = "Prineville Reservoir State Park",
                            NearestCity = "Prineville",
                            RegionId = 3,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 28,
                            Camping = false,
                            Name = "Heritage Landing (Deschutes)",
                            NearestCity = "Prineville",
                            RegionId = 4,
                            Type = "Boat Launch"
                        },
                        new
                        {
                            ParkId = 29,
                            Camping = false,
                            Name = "White River Falls State Park",
                            NearestCity = "The Dalles",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 30,
                            Camping = true,
                            Name = "Deschutes River State Recreation Area",
                            NearestCity = "The Dalles",
                            RegionId = 4,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 31,
                            Camping = false,
                            Name = "Cline Falls State Scenic Viewpoint",
                            NearestCity = "The Dalles",
                            RegionId = 3,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 32,
                            Camping = true,
                            Name = "Fort Rock State Natural Area",
                            NearestCity = "Redmond",
                            RegionId = 3,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 33,
                            Camping = true,
                            Name = "La Pine State Park",
                            NearestCity = "Fort Rock",
                            RegionId = 3,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 34,
                            Camping = false,
                            Name = "Pilot Butte State Scenic Viewpoint",
                            NearestCity = "La Pine",
                            RegionId = 3,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 35,
                            Camping = true,
                            Name = "Tumalo State Park",
                            NearestCity = "Bend",
                            RegionId = 3,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 36,
                            Camping = false,
                            Name = "Peter Skene Ogden State Scenic Viewpoint",
                            NearestCity = "Bend",
                            RegionId = 3,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 37,
                            Camping = true,
                            Name = "Smith Rock State Park",
                            NearestCity = "Redmond",
                            RegionId = 3,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 38,
                            Camping = false,
                            Name = "Booth State Scenic Corridor",
                            NearestCity = "Redmond",
                            RegionId = 1,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 39,
                            Camping = false,
                            Name = "Chandler State Wayside",
                            NearestCity = "Lakeview",
                            RegionId = 1,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 40,
                            Camping = false,
                            Name = "Geisel Monument State Heritage Site",
                            NearestCity = "Lakeview",
                            RegionId = 5,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 41,
                            Camping = true,
                            Name = "Humbug Mountain State Park",
                            NearestCity = "Gold Beach",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 42,
                            Camping = false,
                            Name = "Otter Point State Recreation Site",
                            NearestCity = "Port Orford",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 43,
                            Camping = false,
                            Name = "Paradise Point State Recreation Site",
                            NearestCity = "Gold Beach",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 44,
                            Camping = false,
                            Name = "Port Orford Heads State Park",
                            NearestCity = "Port Orford",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 45,
                            Camping = true,
                            Name = "Cape Blanco State Park",
                            NearestCity = "Port Orford",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 46,
                            Camping = false,
                            Name = "Bandon State Natural Area",
                            NearestCity = "Port Orford",
                            RegionId = 5,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 47,
                            Camping = false,
                            Name = "Coquille Myrtle Grove State Natural Site",
                            NearestCity = "Bandon",
                            RegionId = 5,
                            Type = "Natural Site"
                        },
                        new
                        {
                            ParkId = 48,
                            Camping = false,
                            Name = "Face Rock State Scenic Viewpoint",
                            NearestCity = "Myrtle Point",
                            RegionId = 5,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 49,
                            Camping = false,
                            Name = "Hoffman Memorial State Wayside",
                            NearestCity = "Bandon",
                            RegionId = 5,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 50,
                            Camping = false,
                            Name = "Seven Devils State Recreation Site",
                            NearestCity = "Myrtle Point",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 51,
                            Camping = true,
                            Name = "Bullards Beach State Park",
                            NearestCity = "Bandon",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 52,
                            Camping = true,
                            Name = "Alfred A. Loeb State Park",
                            NearestCity = "Bandon",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 53,
                            Camping = false,
                            Name = "Cape Sebastian State Scenic Corridor",
                            NearestCity = "Brookings",
                            RegionId = 5,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 54,
                            Camping = false,
                            Name = "Crissey Field State Recreation Site",
                            NearestCity = "Gold Beach",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 55,
                            Camping = false,
                            Name = "McVay Rock State Recreation Site",
                            NearestCity = "Brookings",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 56,
                            Camping = false,
                            Name = "Pistol River State Scenic Viewpoint",
                            NearestCity = "Brookings",
                            RegionId = 5,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 57,
                            Camping = false,
                            Name = "Samuel H. Boardman State Scenic Corridor",
                            NearestCity = "Gold Beach",
                            RegionId = 5,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 58,
                            Camping = false,
                            Name = "Winchuck State Recreation Site",
                            NearestCity = "Brookings",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 59,
                            Camping = true,
                            Name = "Harris Beach State Recreation Area",
                            NearestCity = "Brookings",
                            RegionId = 5,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 60,
                            Camping = false,
                            Name = "Alderwood State Wayside",
                            NearestCity = "Brookings",
                            RegionId = 6,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 61,
                            Camping = false,
                            Name = "Elijah Bristow State Park",
                            NearestCity = "Junction City",
                            RegionId = 6,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 62,
                            Camping = false,
                            Name = "Washburne State Wayside",
                            NearestCity = "Eugene",
                            RegionId = 6,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 63,
                            Camping = false,
                            Name = "Mongold Day-Use Area",
                            NearestCity = "Junction City",
                            RegionId = 6,
                            Type = "Boat Launch"
                        },
                        new
                        {
                            ParkId = 64,
                            Camping = false,
                            Name = "North Santiam State Recreation Area",
                            NearestCity = "Detroit",
                            RegionId = 6,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 65,
                            Camping = true,
                            Name = "Detroit Lake State Recreation Area",
                            NearestCity = "Mill City",
                            RegionId = 6,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 66,
                            Camping = false,
                            Name = "Cape Arago State Park",
                            NearestCity = "Detroit",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 67,
                            Camping = false,
                            Name = "Golden and Silver Falls State Natural Area",
                            NearestCity = "Coos Bay",
                            RegionId = 5,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 68,
                            Camping = false,
                            Name = "Shore Acres State Park",
                            NearestCity = "Coos Bay",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 69,
                            Camping = true,
                            Name = "William M. Tugman State Park",
                            NearestCity = "Coos Bay",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 70,
                            Camping = true,
                            Name = "Sunset Bay State Park",
                            NearestCity = "Reedsport",
                            RegionId = 5,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 71,
                            Camping = false,
                            Name = "Illinois River Forks State Park",
                            NearestCity = "Coos Bay",
                            RegionId = 1,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 72,
                            Camping = false,
                            Name = "TouVelle State Recreation Site",
                            NearestCity = "Cave Junction",
                            RegionId = 1,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 73,
                            Camping = false,
                            Name = "Tub Springs State Wayside",
                            NearestCity = "Medford",
                            RegionId = 1,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 74,
                            Camping = false,
                            Name = "Wolf Creek Inn State Heritage Site",
                            NearestCity = "Ashland",
                            RegionId = 1,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 75,
                            Camping = true,
                            Name = "Valley of the Rogue State Recreation Area",
                            NearestCity = "Grants Pass",
                            RegionId = 1,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 76,
                            Camping = false,
                            Name = "Bald Peak State Scenic Viewpoint",
                            NearestCity = "Grants Pass",
                            RegionId = 4,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 77,
                            Camping = false,
                            Name = "Molalla River State Park",
                            NearestCity = "Newberg",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 78,
                            Camping = true,
                            Name = "Champoeg State Heritage Area",
                            NearestCity = "Canby",
                            RegionId = 6,
                            Type = "Heritage Area"
                        },
                        new
                        {
                            ParkId = 79,
                            Camping = false,
                            Name = "Beaver Creek State Natural Area",
                            NearestCity = "Newberg",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 80,
                            Camping = false,
                            Name = "Bolon Island Tideways State Scenic Corridor",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 81,
                            Camping = false,
                            Name = "Darlingtonia State Natural Site",
                            NearestCity = "Reedsport",
                            RegionId = 7,
                            Type = "Natural Site"
                        },
                        new
                        {
                            ParkId = 82,
                            Camping = false,
                            Name = "Governor Patterson Memorial State Recreation Site",
                            NearestCity = "Florence",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 83,
                            Camping = true,
                            Name = "Umpqua Lighthouse State Park",
                            NearestCity = "Waldport",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 84,
                            Camping = true,
                            Name = "Beachside State Recreation Site",
                            NearestCity = "Reedsport",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 85,
                            Camping = true,
                            Name = "Carl G. Washburne Memorial State Park",
                            NearestCity = "Waldport",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 86,
                            Camping = false,
                            Name = "Heceta Head Lighthouse State Scenic Viewpoint",
                            NearestCity = "Florence",
                            RegionId = 7,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 87,
                            Camping = false,
                            Name = "Muriel O. Ponsler Memorial State Scenic Viewpoint",
                            NearestCity = "Florence",
                            RegionId = 7,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 88,
                            Camping = false,
                            Name = "Neptune State Scenic Viewpoint",
                            NearestCity = "Florence",
                            RegionId = 7,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 89,
                            Camping = false,
                            Name = "Smelt Sands State Recreation Site",
                            NearestCity = "Yachats",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 90,
                            Camping = false,
                            Name = "Tokatee Klootchman State Natural Site",
                            NearestCity = "Yachats",
                            RegionId = 7,
                            Type = "Natural Site"
                        },
                        new
                        {
                            ParkId = 91,
                            Camping = false,
                            Name = "Stonefield Beach State Recreation Site",
                            NearestCity = "Florence",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 92,
                            Camping = false,
                            Name = "W. B. Nelson State Recreation Site",
                            NearestCity = "Yachats",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 93,
                            Camping = false,
                            Name = "Yachats Ocean Road State Natural Site",
                            NearestCity = "Waldport",
                            RegionId = 7,
                            Type = "Natural Site"
                        },
                        new
                        {
                            ParkId = 94,
                            Camping = false,
                            Name = "Yachats State Recreation Area",
                            NearestCity = "Yachats",
                            RegionId = 7,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 95,
                            Camping = true,
                            Name = "Jessie M. Honeyman Memorial State Park",
                            NearestCity = "Yachats",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 96,
                            Camping = false,
                            Name = "Erratic Rock State Natural Site",
                            NearestCity = "Florence",
                            RegionId = 6,
                            Type = "Natural Site"
                        },
                        new
                        {
                            ParkId = 97,
                            Camping = false,
                            Name = "Holman State Wayside",
                            NearestCity = "Sheridan",
                            RegionId = 6,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 98,
                            Camping = false,
                            Name = "Maud Williamson State Recreation Site",
                            NearestCity = "Salem",
                            RegionId = 6,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 99,
                            Camping = false,
                            Name = "Sarah Helmick State Recreation Site",
                            NearestCity = "Salem",
                            RegionId = 6,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 100,
                            Camping = false,
                            Name = "Willamette Mission State Park",
                            NearestCity = "Monmouth",
                            RegionId = 6,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 101,
                            Camping = false,
                            Name = "Bonnie Lure State Recreation Area",
                            NearestCity = "Salem",
                            RegionId = 4,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 102,
                            Camping = false,
                            Name = "Mary S. Young State Recreation Area",
                            NearestCity = "Estacada",
                            RegionId = 4,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 103,
                            Camping = true,
                            Name = "Milo McIver State Park",
                            NearestCity = "West Linn",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 104,
                            Camping = false,
                            Name = "Tryon Creek State Natural Area",
                            NearestCity = "Estacada",
                            RegionId = 4,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 105,
                            Camping = false,
                            Name = "Banks–Vernonia State Trail",
                            NearestCity = "Portland",
                            RegionId = 4,
                            Type = "State Trail"
                        },
                        new
                        {
                            ParkId = 106,
                            Camping = true,
                            Name = "Ainsworth State Park",
                            NearestCity = "Vernonia",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 107,
                            Camping = false,
                            Name = "Benson State Recreation Area",
                            NearestCity = "Multnomah Falls",
                            RegionId = 4,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 108,
                            Camping = false,
                            Name = "Bridal Veil Falls State Scenic Viewpoint",
                            NearestCity = "Multnomah Falls",
                            RegionId = 4,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 109,
                            Camping = false,
                            Name = "Crown Point State Scenic Corridor",
                            NearestCity = "Multnomah Falls",
                            RegionId = 4,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 110,
                            Camping = false,
                            Name = "Dabney State Recreation Area",
                            NearestCity = "Troutdale",
                            RegionId = 4,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 111,
                            Camping = false,
                            Name = "George W. Joseph State Natural Area (accessible from Guy W. Talbot State Park)",
                            NearestCity = "Troutdale",
                            RegionId = 4,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 112,
                            Camping = false,
                            Name = "Guy W. Talbot State Park",
                            NearestCity = "Troutdale",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 113,
                            Camping = false,
                            Name = "Historic Columbia River Highway State Trail",
                            NearestCity = "Troutdale",
                            RegionId = 4,
                            Type = "State Trail"
                        },
                        new
                        {
                            ParkId = 114,
                            Camping = false,
                            Name = "John B. Yeon State Scenic Corridor",
                            NearestCity = "Cascade Locks",
                            RegionId = 4,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 115,
                            Camping = false,
                            Name = "Koberg Beach State Recreation Site",
                            NearestCity = "Cascade Locks",
                            RegionId = 4,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 116,
                            Camping = false,
                            Name = "Lewis and Clark State Recreation Site",
                            NearestCity = "Hood River",
                            RegionId = 4,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 117,
                            Camping = false,
                            Name = "Mayer State Park",
                            NearestCity = "Troutdale",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 118,
                            Camping = true,
                            Name = "Memaloose State Park",
                            NearestCity = "The Dalles",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 119,
                            Camping = false,
                            Name = "Portland Women's Forum State Scenic Viewpoint",
                            NearestCity = "The Dalles",
                            RegionId = 4,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 120,
                            Camping = false,
                            Name = "Seneca Fouts Memorial State Natural Area",
                            NearestCity = "Troutdale",
                            RegionId = 4,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 121,
                            Camping = false,
                            Name = "Shepperd's Dell State Natural Area",
                            NearestCity = "Hood River",
                            RegionId = 4,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 122,
                            Camping = false,
                            Name = "Sheridan State Scenic Corridor",
                            NearestCity = "Multnomah Falls",
                            RegionId = 4,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 123,
                            Camping = false,
                            Name = "Starvation Creek State Park",
                            NearestCity = "Cascade Locks",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 124,
                            Camping = true,
                            Name = "Viento State Park",
                            NearestCity = "Hood River",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 125,
                            Camping = false,
                            Name = "Vinzenz Lausmann Memorial State Natural Area",
                            NearestCity = "Hood River",
                            RegionId = 4,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 126,
                            Camping = false,
                            Name = "Wygant State Natural Area",
                            NearestCity = "Hood River",
                            RegionId = 4,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 127,
                            Camping = false,
                            Name = "Rooster Rock State Park",
                            NearestCity = "Hood River",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 128,
                            Camping = false,
                            Name = "Bradley State Scenic Viewpoint",
                            NearestCity = "Multnomah Falls",
                            RegionId = 8,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 129,
                            Camping = false,
                            Name = "Del Rey Beach State Recreation Site",
                            NearestCity = "Astoria",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 130,
                            Camping = true,
                            Name = "Fort Stevens State Park",
                            NearestCity = "Gearhart",
                            RegionId = 8,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 131,
                            Camping = false,
                            Name = "Cape Kiwanda State Natural Area",
                            NearestCity = "Astoria",
                            RegionId = 8,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 132,
                            Camping = false,
                            Name = "Cape Meares State Scenic Viewpoint",
                            NearestCity = "Pacific City",
                            RegionId = 8,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 133,
                            Camping = false,
                            Name = "Oceanside Beach State Recreation Site",
                            NearestCity = "Tillamook",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 134,
                            Camping = false,
                            Name = "Bob Straub State Park",
                            NearestCity = "Tillamook",
                            RegionId = 8,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 135,
                            Camping = true,
                            Name = "Cape Lookout State Park",
                            NearestCity = "Pacific City",
                            RegionId = 8,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 136,
                            Camping = false,
                            Name = "Arcadia Beach State Recreation Site",
                            NearestCity = "Tillamook",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 137,
                            Camping = false,
                            Name = "Ecola State Park",
                            NearestCity = "Cannon Beach",
                            RegionId = 8,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 138,
                            Camping = false,
                            Name = "Golden State Heritage Site",
                            NearestCity = "Cannon Beach",
                            RegionId = 1,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 139,
                            Camping = false,
                            Name = "Hug Point State Recreation Site",
                            NearestCity = "Grants Pass",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 140,
                            Camping = false,
                            Name = "Manhattan Beach State Recreation Site",
                            NearestCity = "Cannon Beach",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 141,
                            Camping = false,
                            Name = "Oswald West State Park",
                            NearestCity = "Rockaway Beach",
                            RegionId = 8,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 142,
                            Camping = true,
                            Name = "Saddle Mountain State Natural Area",
                            NearestCity = "Cannon Beach",
                            RegionId = 8,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 143,
                            Camping = false,
                            Name = "Tolovana Beach State Recreation Site",
                            NearestCity = "Seaside",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 144,
                            Camping = true,
                            Name = "Nehalem Bay State Park",
                            NearestCity = "Cannon Beach",
                            RegionId = 8,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 145,
                            Camping = false,
                            Name = "Alsea Bay Historic Interpretive Center",
                            NearestCity = "Manzanita",
                            RegionId = 7,
                            Type = "Interpretive Center"
                        },
                        new
                        {
                            ParkId = 146,
                            Camping = false,
                            Name = "Driftwood Beach State Recreation Site",
                            NearestCity = "Waldport",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 147,
                            Camping = false,
                            Name = "Lost Creek State Recreation Site",
                            NearestCity = "Waldport",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 148,
                            Camping = false,
                            Name = "Ona Beach State Park",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 149,
                            Camping = false,
                            Name = "Seal Rock State Recreation Site",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 150,
                            Camping = false,
                            Name = "Yaquina Bay State Recreation Site",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 151,
                            Camping = true,
                            Name = "South Beach State Park",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 152,
                            Camping = true,
                            Name = "Cascadia State Park",
                            NearestCity = "Newport",
                            RegionId = 6,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 153,
                            Camping = true,
                            Name = "Silver Falls State Park",
                            NearestCity = "Sweet Home",
                            RegionId = 6,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 154,
                            Camping = false,
                            Name = "Agate Beach State Recreation Site",
                            NearestCity = "Silverton",
                            RegionId = 7,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 155,
                            Camping = false,
                            Name = "Boiler Bay State Scenic Viewpoint",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 156,
                            Camping = false,
                            Name = "D River State Recreation Site",
                            NearestCity = "Depoe Bay",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 157,
                            Camping = true,
                            Name = "Devils Lake State Recreation Area",
                            NearestCity = "Lincoln City",
                            RegionId = 8,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 158,
                            Camping = false,
                            Name = "Devils Punch Bowl State Natural Area",
                            NearestCity = "Lincoln City",
                            RegionId = 7,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 159,
                            Camping = false,
                            Name = "Ellmaker State Wayside",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 160,
                            Camping = false,
                            Name = "Fogarty Creek State Recreation Area",
                            NearestCity = "Newport",
                            RegionId = 7,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 161,
                            Camping = false,
                            Name = "Gleneden Beach State Recreation Site",
                            NearestCity = "Depoe Bay",
                            RegionId = 7,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 162,
                            Camping = false,
                            Name = "H. B. Van Duzer Forest State Scenic Corridor",
                            NearestCity = "Lincoln City",
                            RegionId = 8,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 163,
                            Camping = false,
                            Name = "Neskowin Beach State Recreation Site",
                            NearestCity = "Lincoln City",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 164,
                            Camping = false,
                            Name = "Otter Crest State Scenic Viewpoint",
                            NearestCity = "Neskowin",
                            RegionId = 7,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 165,
                            Camping = false,
                            Name = "Roads End State Recreation Site",
                            NearestCity = "Newport",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 166,
                            Camping = true,
                            Name = "Beverly Beach State Park",
                            NearestCity = "Lincoln City",
                            RegionId = 7,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 167,
                            Camping = true,
                            Name = "Collier Memorial State Park",
                            NearestCity = "Newport",
                            RegionId = 1,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 168,
                            Camping = true,
                            Name = "Jackson F. Kimball State Recreation Site",
                            NearestCity = "Klamath Falls",
                            RegionId = 1,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 169,
                            Camping = false,
                            Name = "OC&E Woods Line State Trail",
                            NearestCity = "Fort Klamath",
                            RegionId = 1,
                            Type = "State Trail"
                        },
                        new
                        {
                            ParkId = 170,
                            Camping = false,
                            Name = "South Jetty (South Beach)",
                            NearestCity = "Klamath Falls",
                            RegionId = 7,
                            Type = "Beach Access"
                        },
                        new
                        {
                            ParkId = 171,
                            Camping = false,
                            Name = "Blue Mountain Forest State Scenic Corridor",
                            NearestCity = "Newport",
                            RegionId = 2,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 172,
                            Camping = false,
                            Name = "Battle Mountain Forest State Scenic Corridor",
                            NearestCity = "La Grande",
                            RegionId = 2,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 173,
                            Camping = false,
                            Name = "Sumpter Valley Dredge State Heritage Area",
                            NearestCity = "Ukiah",
                            RegionId = 2,
                            Type = "Heritage Area"
                        },
                        new
                        {
                            ParkId = 174,
                            Camping = true,
                            Name = "Fall Creek State Recreation Site",
                            NearestCity = "Baker City",
                            RegionId = 6,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 175,
                            Camping = false,
                            Name = "Lowell State Recreation Site",
                            NearestCity = "Springfield",
                            RegionId = 6,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 176,
                            Camping = false,
                            Name = "Jasper State Recreation Site",
                            NearestCity = "Springfield",
                            RegionId = 6,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 177,
                            Camping = false,
                            Name = "Dexter State Recreation Site",
                            NearestCity = "Springfield",
                            RegionId = 6,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 178,
                            Camping = false,
                            Name = "Munson Creek Falls State Natural Site",
                            NearestCity = "Springfield",
                            RegionId = 8,
                            Type = "Natural Site"
                        },
                        new
                        {
                            ParkId = 179,
                            Camping = false,
                            Name = "Willamette Stone State Heritage Site",
                            NearestCity = "Tillamook",
                            RegionId = 4,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 180,
                            Camping = false,
                            Name = "Umpqua State Scenic Corridor",
                            NearestCity = "Portland",
                            RegionId = 5,
                            Type = "Scenic Corridor"
                        },
                        new
                        {
                            ParkId = 181,
                            Camping = false,
                            Name = "Clay Myers State Natural Area at Whalen Island",
                            NearestCity = "Reedsport",
                            RegionId = 8,
                            Type = "Natural Area"
                        },
                        new
                        {
                            ParkId = 182,
                            Camping = false,
                            Name = "Fort Rock Cave (Near Fort Rock State Natural Area)",
                            NearestCity = "Pacific City",
                            RegionId = 3,
                            Type = "National Historic Landmark"
                        },
                        new
                        {
                            ParkId = 183,
                            Camping = true,
                            Name = "Government Island State Recreation Area",
                            NearestCity = "Fort Rock",
                            RegionId = 4,
                            Type = "Recreation Area"
                        },
                        new
                        {
                            ParkId = 184,
                            Camping = false,
                            Name = "Sunset Beach State Recreation Site",
                            NearestCity = "Portland",
                            RegionId = 8,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 185,
                            Camping = false,
                            Name = "Whale Watching Center",
                            NearestCity = "Astoria",
                            RegionId = 7,
                            Type = "Guided Ocean Viewpoint"
                        },
                        new
                        {
                            ParkId = 186,
                            Camping = false,
                            Name = "Rocky Creek State Scenic Viewpoint",
                            NearestCity = "Depoe Bay",
                            RegionId = 7,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 187,
                            Camping = false,
                            Name = "Fort Yamhill State Heritage Area",
                            NearestCity = "Depoe Bay",
                            RegionId = 6,
                            Type = "Heritage Area"
                        },
                        new
                        {
                            ParkId = 188,
                            Camping = true,
                            Name = "L. L. 'Stub' Stewart State Park",
                            NearestCity = "Grand Ronde",
                            RegionId = 4,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 189,
                            Camping = false,
                            Name = "Thompson's Mills State Heritage Site",
                            NearestCity = "Vernonia",
                            RegionId = 6,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 190,
                            Camping = false,
                            Name = "State Capitol State Park",
                            NearestCity = "Shedd",
                            RegionId = 6,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 191,
                            Camping = false,
                            Name = "Arizona Beach State Recreation Site",
                            NearestCity = "Salem",
                            RegionId = 5,
                            Type = "Recreation Site"
                        },
                        new
                        {
                            ParkId = 192,
                            Camping = false,
                            Name = "Bates State Park",
                            NearestCity = "Port Orford",
                            RegionId = 2,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 193,
                            Camping = false,
                            Name = "Ochoco State Scenic Viewpoint",
                            NearestCity = "Prairie City",
                            RegionId = 3,
                            Type = "Scenic Viewpoint"
                        },
                        new
                        {
                            ParkId = 194,
                            Camping = false,
                            Name = "Dyer State Wayside",
                            NearestCity = "Prineville",
                            RegionId = 2,
                            Type = "Wayside"
                        },
                        new
                        {
                            ParkId = 195,
                            Camping = false,
                            Name = "Pete French Round Barn State Heritage Site",
                            NearestCity = "Condon",
                            RegionId = 2,
                            Type = "Heritage Site"
                        },
                        new
                        {
                            ParkId = 196,
                            Camping = false,
                            Name = "Cottonwood Canyon State Park",
                            NearestCity = "New Princeton",
                            RegionId = 3,
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 197,
                            Camping = false,
                            Name = "Sitka Sedge State Natural Area",
                            NearestCity = "Moro",
                            RegionId = 8,
                            Type = "Natural Site"
                        });
                });

            modelBuilder.Entity("StatePark.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Southern Oregon"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Eastern Oregon"
                        },
                        new
                        {
                            RegionId = 3,
                            Name = "Central Oregon"
                        },
                        new
                        {
                            RegionId = 4,
                            Name = "Portland/Columbia Gorge"
                        },
                        new
                        {
                            RegionId = 5,
                            Name = "South Coast"
                        },
                        new
                        {
                            RegionId = 6,
                            Name = "Willamette Valley"
                        },
                        new
                        {
                            RegionId = 7,
                            Name = "Central Coast"
                        },
                        new
                        {
                            RegionId = 8,
                            Name = "North Coast"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
